package fql_lib.examples;

import fql_lib.ide.Example;
import fql_lib.ide.Language;

public class Patrick19ExampleNist2 extends Example {

	@Override
	public Language lang() {
		return Language.FPQL;
	}

	
	@Override
	public String getName() {
		return "NIST IsA";
	}

	@Override
	public String getText() {
		return s;
	}
	
	String s = "adom : type"
			+ "\n"
			+ "\nGlassCeramics: adom"
			+ "\nGlass: adom"
			+ "\nCrystalline: adom"
			+ "\nNonCrystalline: adom"
			+ "\nCeramic: adom"
			+ "\nComposite: adom"
			+ "\nMetal: adom"
			+ "\nFerrous: adom"
			+ "\nCastIron: adom"
			+ "\nDieSteel: adom"
			+ "\nSteel: adom"
			+ "\nToolSteel: adom"
			+ "\nStainlessSteel: adom"
			+ "\nNonFerrous: adom"
			+ "\nSuperAlloy: adom"
			+ "\nStellite : adom"
			+ "\nIconel: adom"
			+ "\nHastelloy: adom"
			+ "\nElastomer: adom"
			+ "\nPlastic: adom"
			+ "\nPolymer: adom"
			+ "\nHermoset: adom"
			+ "\nThermoPlastic: adom"
			+ "\nNylon: adom"
			+ "\nPVC: adom"
			+ "\nPolyester: adom"
			+ "\nMaterial: adom"
			+ "\n"
			+ "\n///////////////////////////////////////"
			+ "\n"
			+ "\nisa_preschema = schema {"
			+ "\n	nodes B;"
			+ "\n	edges f : B -> B, name : B -> adom;"
			+ "\n	equations f.f.f.f.f = f.f.f.f;"
			+ "\n}"
			+ "\n"
			+ "\nisa_pre = instance {"
			+ "\n	variables"
			+ "\n	vGlassCeramics"
			+ "\n	vGlass"
			+ "\n	vCrystalline"
			+ "\n	vNonCrystalline"
			+ "\n	vCeramic"
			+ "\n	vComposite"
			+ "\n	vMetal"
			+ "\n	vFerrous"
			+ "\n	vCastIron"
			+ "\n	vDieSteel"
			+ "\n	vSteel"
			+ "\n	vToolSteel"
			+ "\n	vStainlessSteel"
			+ "\n	vNonFerrous"
			+ "\n	vSuperAlloy"
			+ "\n	vStellite "
			+ "\n	vIconel"
			+ "\n	vHastelloy"
			+ "\n	vElastomer"
			+ "\n	vPlastic"
			+ "\n	vPolymer"
			+ "\n	vHermoset"
			+ "\n	vThermoPlastic"
			+ "\n	vNylon"
			+ "\n	vPVC"
			+ "\n	vPolyester"
			+ "\n	vMaterial: B;"
			+ "\n	equations"
			+ "\n	vGlassCeramics.name = GlassCeramics,"
			+ "\n	vGlass.name = Glass,"
			+ "\n	vCrystalline.name = Crystalline,"
			+ "\n	vNonCrystalline.name = NonCrystalline,"
			+ "\n	vCeramic.name = Ceramic,"
			+ "\n	vComposite.name = Composite,"
			+ "\n	vMetal.name = Metal,"
			+ "\n	vFerrous.name = Ferrous,"
			+ "\n	vCastIron.name = CastIron,"
			+ "\n	vDieSteel.name = DieSteel, "
			+ "\n	vSteel.name = Steel,"
			+ "\n	vToolSteel.name = ToolSteel,"
			+ "\n	vStainlessSteel.name = StainlessSteel,"
			+ "\n	vNonFerrous.name = NonFerrous,"
			+ "\n	vSuperAlloy.name = SuperAlloy,"
			+ "\n	vStellite.name = Stellite,"
			+ "\n	vIconel.name = Iconel,"
			+ "\n	vHastelloy.name = Hastelloy,"
			+ "\n	vElastomer.name = Elastomer,"
			+ "\n	vPlastic.name = Plastic,"
			+ "\n	vPolymer.name = Polymer,"
			+ "\n	vHermoset.name = Hermoset,"
			+ "\n	vThermoPlastic.name = ThermoPlastic,"
			+ "\n	vNylon.name = Nylon,"
			+ "\n	vPVC.name = PVC,"
			+ "\n	vPolyester.name = Polyester,"
			+ "\n	vMaterial.name = Material,"
			+ "\n	vGlassCeramics.f = vNonCrystalline, "
			+ "\n	vGlass.f = vNonCrystalline, "
			+ "\n	vCrystalline.f = vCeramic, "
			+ "\n	vNonCrystalline.f = vCeramic, "
			+ "\n	vCeramic.f = vMaterial, "
			+ "\n	vComposite.f = vMaterial, "
			+ "\n	vMetal.f = vMaterial, "
			+ "\n	vFerrous.f = vMetal, "
			+ "\n	vNonFerrous.f = vMetal, "
			+ "\n	vSuperAlloy.f = vMetal, "
			+ "\n	vCastIron.f = vFerrous, "
			+ "\n	vDieSteel.f = vFerrous,"
			+ "\n	vSteel.f = vFerrous, "
			+ "\n	vToolSteel.f = vFerrous,"
			+ "\n	vStainlessSteel.f = vSteel,"
			+ "\n	vNonFerrous.f = vMetal, "
			+ "\n	vSuperAlloy.f = vMetal,"
			+ "\n	vStellite.f = vSuperAlloy, "
			+ "\n	vIconel.f = vSuperAlloy, "
			+ "\n	vHastelloy.f = vSuperAlloy,"
			+ "\n	vElastomer.f = vPolymer, "
			+ "\n	vPlastic.f = vPolymer, "
			+ "\n	vPolymer.f = vMaterial,"
			+ "\n	vHermoset.f = vPlastic, "
			+ "\n	vThermoPlastic.f = vPlastic,"
			+ "\n	vNylon.f = vThermoPlastic, "
			+ "\n	vPVC.f = vThermoPlastic, "
			+ "\n	vPolyester.f = vThermoPlastic,"
			+ "\n	vMaterial.f = vMaterial;"
			+ "\n} : isa_preschema"
			+ "\n"
			+ "\nisa_schema = schema {"
			+ "\n	nodes A, B;"
			+ "\n	edges l : A -> B, r : A -> B, name : B -> adom;"
			+ "\n	equations;"
			+ "\n}"
			+ "\n"
			+ "\n//////////////////////////////////////////////////////"
			+ "\n"
			+ "\nisa = INSTANCE {"
			+ "\n	variables v1 v2 v3 v4 v5 v6 v7 v8 v11 v12 v13 v14 v15 v16 v17 v18 v19 v20 v21 v22 v23 v24 v25 v26 v27 v28 v29 : A,"
			+ "\n	vGlassCeramics"
			+ "\n	vGlass"
			+ "\n	vCrystalline"
			+ "\n	vNonCrystalline"
			+ "\n	vCeramic"
			+ "\n	vComposite"
			+ "\n	vMetal"
			+ "\n	vFerrous"
			+ "\n	vCastIron"
			+ "\n	vDieSteel"
			+ "\n	vSteel"
			+ "\n	vToolSteel"
			+ "\n	vStainlessSteel"
			+ "\n	vNonFerrous"
			+ "\n	vSuperAlloy"
			+ "\n	vStellite "
			+ "\n	vIconel"
			+ "\n	vHastelloy"
			+ "\n	vElastomer"
			+ "\n	vPlastic"
			+ "\n	vPolymer"
			+ "\n	vHermoset"
			+ "\n	vThermoPlastic"
			+ "\n	vNylon"
			+ "\n	vPVC"
			+ "\n	vPolyester"
			+ "\n	vMaterial: B;"
			+ "\n	equations"
			+ "\n	vGlassCeramics.name = GlassCeramics,"
			+ "\n	vGlass.name = Glass,"
			+ "\n	vCrystalline.name = Crystalline,"
			+ "\n	vNonCrystalline.name = NonCrystalline,"
			+ "\n	vCeramic.name = Ceramic,"
			+ "\n	vComposite.name = Composite,"
			+ "\n	vMetal.name = Metal,"
			+ "\n	vFerrous.name = Ferrous,"
			+ "\n	vCastIron.name = CastIron,"
			+ "\n	vDieSteel.name = DieSteel, "
			+ "\n	vSteel.name = Steel,"
			+ "\n	vToolSteel.name = ToolSteel,"
			+ "\n	vStainlessSteel.name = StainlessSteel,"
			+ "\n	vNonFerrous.name = NonFerrous,"
			+ "\n	vSuperAlloy.name = SuperAlloy,"
			+ "\n	vStellite.name = Stellite,"
			+ "\n	vIconel.name = Iconel,"
			+ "\n	vHastelloy.name = Hastelloy,"
			+ "\n	vElastomer.name = Elastomer,"
			+ "\n	vPlastic.name = Plastic,"
			+ "\n	vPolymer.name = Polymer,"
			+ "\n	vHermoset.name = Hermoset,"
			+ "\n	vThermoPlastic.name = ThermoPlastic,"
			+ "\n	vNylon.name = Nylon,"
			+ "\n	vPVC.name = PVC,"
			+ "\n	vPolyester.name = Polyester,"
			+ "\n	vMaterial.name = Material,"
			+ "\n	v1.l = vGlassCeramics, v1.r = vNonCrystalline, "
			+ "\n	v2.l = vGlass, v2.r = vNonCrystalline, "
			+ "\n	v3.l = vCrystalline, v3.r = vCeramic, "
			+ "\n	v4.l = vNonCrystalline, v4.r = vCeramic, "
			+ "\n	v5.l = vCeramic, v5.r = vMaterial, "
			+ "\n	v6.l = vComposite, v6.r = vMaterial, "
			+ "\n	v7.l = vMetal, v7.r = vMaterial, "
			+ "\n	v8.l = vFerrous, v8.r = vMetal, "
			+ "\n	v11.l= vCastIron, v11.r = vFerrous, "
			+ "\n	v12.l= vDieSteel, v12.r = vFerrous,"
			+ "\n	v13.l= vSteel, v13.r = vFerrous, "
			+ "\n	v14.l= vToolSteel, v14.r = vFerrous,"
			+ "\n	v15.l= vStainlessSteel, v15.r = vSteel,"
			+ "\n	v16.l= vNonFerrous, v16.r = vMetal, "
			+ "\n	v17.l= vSuperAlloy, v17.r = vMetal,"
			+ "\n	v18.l= vStellite, v18.r = vSuperAlloy, "
			+ "\n	v19.l= vIconel, v19.r = vSuperAlloy, "
			+ "\n	v20.l= vHastelloy, v20.r = vSuperAlloy,"
			+ "\n	v21.l= vElastomer, v21.r = vPolymer, "
			+ "\n	v22.l= vPlastic, v22.r = vPolymer, "
			+ "\n	v23.l= vPolymer, v23.r = vMaterial,"
			+ "\n	v24.l= vHermoset, v24.r = vPlastic, "
			+ "\n	v25.l= vThermoPlastic, v25.r = vPlastic,"
			+ "\n	v26.l= vNylon, v26.r = vThermoPlastic, "
			+ "\n	v27.l= vPVC, v27.r = vThermoPlastic, "
			+ "\n	v28.l= vPolyester, v28.r = vThermoPlastic,"
			+ "\n	v29.l= vMaterial, v29.r = vMaterial;"
			+ "\n} : isa_schema"
			+ "\n"
			+ "\n//////////"
			+ "\n"
			+ "\nisa_schema_small = schema {"
			+ "\n	nodes A;"
			+ "\n	edges l : A -> adom, r : A -> adom;"
			+ "\n	equations;"
			+ "\n}"
			+ "\n"
			+ "\nM = mapping {"
			+ "\n	nodes A -> A;"
			+ "\n	edges l -> l.name, r -> r.name;"
			+ "\n} : isa_schema_small -> isa_schema "
			+ "\n"
			+ "\nisa_small = delta M isa"
			+ "\n"
			+ "\n//////////"
			+ "\n"
			+ "\nL0 = mapping {"
			+ "\n	nodes A -> B, B -> B;"
			+ "\n	edges l -> B, r -> B, name -> name;"
			+ "\n} : isa_schema -> isa_preschema"
			+ "\n"
			+ "\n"
			+ "\nL1 = mapping {"
			+ "\n	nodes A -> B, B -> B;"
			+ "\n	edges l -> B, r -> f, name -> name;"
			+ "\n} : isa_schema -> isa_preschema"
			+ "\n"
			+ "\nL2 = mapping {"
			+ "\n	nodes A -> B, B -> B;"
			+ "\n	edges l -> B, r -> f.f, name -> name;"
			+ "\n} : isa_schema -> isa_preschema"
			+ "\n"
			+ "\nL3 = mapping {"
			+ "\n	nodes A -> B, B -> B;"
			+ "\n	edges l -> B, r -> f.f.f, name -> name;"
			+ "\n} : isa_schema -> isa_preschema"
			+ "\n"
			+ "\nisa_rt0 = delta L0 isa_pre"
			+ "\nisa_rt1 = delta L1 isa_pre "
			+ "\nisa_rt2 = delta L2 isa_pre"
			+ "\nisa_rt3 = delta L3 isa_pre"
			+ "\n"
			+ "\nisa_rt = relationalize (isa_rt0 + (isa_rt1 + (isa_rt2 + isa_rt3)))"
			+ "\n"
			+ "\n///////////"
			+ "\n"
			+ "\nisa_rt_small = delta M isa_rt"
			+ "\n";

}
