package fql_lib.examples;

public class Patrick15Example extends Example {

	@Override
	public boolean isPatrick() {
		return true;
	}
	
	@Override
	public String getName() {
		return "P NIST";
	}

	@Override
	public String getText() {
		return s;
	}
	
	String s = "//takes a few minutes to load initial data"
			+ "\nadom : type"
			+ "\n"
			+ "\n\"Micro Hole EDM\" : adom"
			+ "\n\"Forging Dies\" : adom"
			+ "\n\"Honing Machine\" : adom"
			+ "\n\"A-2 Tool Steel\" : adom"
			+ "\n\"Plastic Mold Making Services\" : adom"
			+ "\n\"Ram EDM\" : adom"
			+ "\n\"A-6 Tool Steel\" : adom"
			+ "\n\"Blow Molds (Extrusion or Injection/Blow)\" : adom"
			+ "\n\"300 Stainless Steel\" : adom"
			+ "\n\"4140 Alloy Steels\" : adom"
			+ "\n\"Titanium\" : adom"
			+ "\n\"I used the types of molds values from the Canyon Plastics.\" : adom"
			+ "\n\"304 Stainless Steel\" : adom"
			+ "\n\"Possible error\" : adom"
			+ "\n\"Non-Ferrous\" : adom"
			+ "\n\"Tecomet\" : adom"
			+ "\n\"Inch\" : adom"
			+ "\n\"Wire EDM\" : adom"
			+ "\n\"Verticle CNC Milling Machine\" : adom"
			+ "\n\"Forgings\" : adom"
			+ "\n0 : adom"
			+ "\n\"Surface Grinder\" : adom"
			+ "\n\"Titanium Alloy CP4\" : adom"
			+ "\n\"Length measure in inches\" : adom"
			+ "\n\"mm\" : adom"
			+ "\n1 : adom"
			+ "\n\"Each part/piece count\" : adom"
			+ "\n\"CNC Machining\" : adom"
			+ "\n\"0.005\" : adom"
			+ "\n\"Pro Mold\" : adom"
			+ "\n\"Marine\" : adom"
			+ "\n20 : adom"
			+ "\n\"\" : adom"
			+ "\n\"17-4 Stainless Steel\" : adom"
			+ "\n\"P-20\" : adom"
			+ "\n\"Transfer/Compression (Rubber or Silicone)\" : adom"
			+ "\n\"Extrusion Dies\" : adom"
			+ "\n\"Extrusions\" : adom"
			+ "\n1000 : adom"
			+ "\n\"15-4 Stainless Steel\" : adom"
			+ "\n\"Small Hole EDM\" : adom"
			+ "\n\"D2 Tool Steel\" : adom"
			+ "\n\"Machining\" : adom"
			+ "\n\"Rotary Dies\" : adom"
			+ "\n\"Plunger EDM\" : adom"
			+ "\n\"Others\" : adom"
			+ "\n\"This supplier has another capability registered under the Injection Molds category, but it is more about molding rather than making the mold. So I excluded that. It also has a separate capability profile about mold design that I excluded.\" : adom"
			+ "\n\"Multi-Cavity/Family Injection Molds\" : adom"
			+ "\n\"Lathe\" : adom"
			+ "\n\"Optical\" : adom"
			+ "\n\"Fully Hardened Tool Steel\" : adom"
			+ "\n\"Titanium Alloy Ti 6AI-4V\" : adom"
			+ "\n\"Collapsible Core\" : adom"
			+ "\n\"High Speed Small Hole EDM\" : adom"
			+ "\n\"Tool Steel 4340\" : adom"
			+ "\n\"Food Processing\" : adom"
			+ "\n\"Liquid Silicone Molds\" : adom"
			+ "\n\"Aluminum\" : adom"
			+ "\n\"Stainless Steel 302\" : adom"
			+ "\n\"4130 Tool Steel\" : adom"
			+ "\n\"CNC 3-axis Milling Machine\" : adom"
			+ "\n\"Pre-hardened Steel\" : adom"
			+ "\n\"Chrome\" : adom"
			+ "\n\"EDM Drilling\" : adom"
			+ "\n\"Brass\" : adom"
			+ "\n\"0.000001\" : adom"
			+ "\n40 : adom"
			+ "\n\"Die Cast Molds\" : adom"
			+ "\n\"Mold Design and Build\" : adom"
			+ "\n\"Alloy Steel\" : adom"
			+ "\n\"No unit\" : adom"
			+ "\n\"Electrical\" : adom"
			+ "\n\"Stainless Steel 300 Series\" : adom"
			+ "\n\"Carbon Steel\" : adom"
			+ "\n\"Wire Electrical Discharge Machining\" : adom"
			+ "\n\"EDM\" : adom"
			+ "\n\"Aerospace\" : adom"
			+ "\n\"Astro\" : adom"
			+ "\n\"Complex & Difficult Machining\" : adom"
			+ "\n\"47.25\" : adom"
			+ "\n\"B&B\" : adom"
			+ "\n\"Wiegel Tool\" : adom"
			+ "\n\"Length measure in millimeters\" : adom"
			+ "\n\"Plastics\" : adom"
			+ "\n\"Columbium\" : adom"
			+ "\n\"Industrial\" : adom"
			+ "\n\"Plastic Injection\" : adom"
			+ "\n\"Stainless Steel\" : adom"
			+ "\n\"Injection Molds\" : adom"
			+ "\n\"0.001\" : adom"
			+ "\n\"Cobalt\" : adom"
			+ "\n\"Automotive\" : adom"
			+ "\n\"Klann Plastics and Canyon Plastics\" : adom"
			+ "\n\"Custom  Molds for Plastic, Rubber, and Die Cast parts\" : adom"
			+ "\n\"Medical\" : adom"
			+ "\n\"EA\" : adom"
			+ "\n\"Communication\" : adom"
			+ "\n\"Prototype and Production Mold Design & Manufacturing\" : adom"
			+ "\n\"Electrical Connectors\" : adom"
			+ "\n\"Custom Manufacturing & Fabricating\" : adom"
			+ "\n\"Hot Runners\" : adom"
			+ "\n\"Music\" : adom"
			+ "\n\"Dies & Molds\" : adom"
			+ "\n\"Electrode Machining\" : adom"
			+ "\n\"Military/Government\" : adom"
			+ "\n1000000 : adom"
			+ "\n\"Thousands\" : adom"
			+ "\n\"Commercial\" : adom"
			+ "\n\"Castings\" : adom"
			+ "\n\"18.25\" : adom"
			+ "\n\"CNC 4-axis Milling Machine\" : adom"
			+ "\n\"Industrial Tools & Die\" : adom"
			+ "\n\"Sinker EDM\" : adom"
			+ "\n\"Building/Construction\" : adom"
			+ "\n\"CR/HR Steel\" : adom"
			+ "\n\"Electronic\" : adom"
			+ "\n\"0.0025\" : adom"
			+ "\n\"CNC & Conventional Machining (turning & milling)\" : adom"
			+ "\n\"General machining\" : adom"
			+ "\n\"Bobs Design\" : adom"
			+ "\n\"Machinery Tools & Supplies\" : adom"
			+ "\n\"Electrical Discharge Machining Services\" : adom"
			+ "\n\"M2 Tool Steel\" : adom"
			+ "\n\"NULL\" : adom"
			+ "\n\"Titanium Alloy CP2\" : adom"
			+ "\n\"NULL - WTF\" : adom"
			+ "\n\"S7 Tool Steel\" : adom"
			+ "\n\"Engraving Machine\" : adom"
			+ "\n\"Consumer Goods\" : adom"
			+ "\n\"Recreational Vehicle\" : adom"
			+ "\n\"316 Stainless Steel\" : adom"
			+ "\n\"Jig Grinder\" : adom"
			+ "\n\"Ferrous\" : adom"
			+ "\n\"1000 parts/pieces count\" : adom"
			+ "\n\"Titanium Alloy Ti 6AI-4V ELI\" : adom"
			+ "\n\"H-13 Tool Steel\" : adom"
			+ "\n\"Tool Steel\" : adom"
			+ "\n\"Inserts Only\" : adom"
			+ "\n"
			+ "\nS = schema {"
			+ "\n nodes"
			+ "\n  unitcode,"
			+ "\n  productorservicecategory,"
			+ "\n  equipmenttype,"
			+ "\n  industry,"
			+ "\n  material,"
			+ "\n  moldtypes,"
			+ "\n  process,"
			+ "\n  supplier,"
			+ "\n  capability,"
			+ "\n  capabilitycategories,"
			+ "\n  capabilityequipment,"
			+ "\n  capabilityindustry,"
			+ "\n  capabilitymaterials,"
			+ "\n  capabilityprocesses,"
			+ "\n  capabilitytypesofmolds,"
			+ "\n  suppliercapabilities;"
			+ "\n edges"
			+ "\n  productorservicecategory_Parent_id: productorservicecategory -> productorservicecategory,"
			+ "\n  capability_Parent_id: capability -> capability,"
			+ "\n  capability_Production_Volume_Min_Unit: capability -> unitcode,"
			+ "\n  capability_Production_Volume_Max_Unit: capability -> unitcode,"
			+ "\n  capability_Max_Length_Unit: capability -> unitcode,"
			+ "\n  capability_Tolerance_Unit: capability -> unitcode,"
			+ "\n  capabilitycategories_Capability_id: capabilitycategories -> capability,"
			+ "\n  capabilitycategories_ProductOrServiceCategory_id: capabilitycategories -> productorservicecategory,"
			+ "\n  capabilityequipment_Capability_id: capabilityequipment -> capability,"
			+ "\n  capabilityequipment_EquipmentType_id: capabilityequipment -> equipmenttype,"
			+ "\n  capabilityindustry_Capability_id: capabilityindustry -> capability,"
			+ "\n  capabilityindustry_Industry_id: capabilityindustry -> industry,"
			+ "\n  capabilitymaterials_Capability_id: capabilitymaterials -> capability,"
			+ "\n  capabilitymaterials_Material_id: capabilitymaterials -> material,"
			+ "\n  capabilityprocesses_Capability_id: capabilityprocesses -> capability,"
			+ "\n  capabilityprocesses_Process_id: capabilityprocesses -> process,"
			+ "\n  capabilitytypesofmolds_Capability_id: capabilitytypesofmolds -> capability,"
			+ "\n  capabilitytypesofmolds_MoldTypes_id: capabilitytypesofmolds -> moldtypes,"
			+ "\n  suppliercapabilities_Supplier_id: suppliercapabilities -> supplier,"
			+ "\n  suppliercapabilities_Capability_id: suppliercapabilities -> capability,"
			+ "\n  unitcode_Code: unitcode -> adom,"
			+ "\n  unitcode_Description: unitcode -> adom,"
			+ "\n  productorservicecategory_Category_Name: productorservicecategory -> adom,"
			+ "\n  productorservicecategory_isLeaf: productorservicecategory -> adom,"
			+ "\n  equipmenttype_EquipmentType_Name: equipmenttype -> adom,"
			+ "\n  industry_Industry_Name: industry -> adom,"
			+ "\n  material_Material_Name: material -> adom,"
			+ "\n  moldtypes_MoldTypes_Name: moldtypes -> adom,"
			+ "\n  process_Process_Name: process -> adom,"
			+ "\n  supplier_Source: supplier -> adom,"
			+ "\n  supplier_Note: supplier -> adom,"
			+ "\n  capability_Capability_Name: capability -> adom,"
			+ "\n  capability_Production_Volume_Min: capability -> adom,"
			+ "\n  capability_Production_Volume_Max: capability -> adom,"
			+ "\n  capability_Max_Length: capability -> adom,"
			+ "\n  capability_Tolerance: capability -> adom;"
			+ "\n equations"
			+ "\n  productorservicecategory.productorservicecategory_Parent_id.productorservicecategory_Parent_id.productorservicecategory_Parent_id = productorservicecategory.productorservicecategory_Parent_id.productorservicecategory_Parent_id.productorservicecategory_Parent_id.productorservicecategory_Parent_id,"
			+ "\n  capability.capability_Parent_id.capability_Parent_id.capability_Parent_id = capability.capability_Parent_id.capability_Parent_id.capability_Parent_id.capability_Parent_id;"
			+ "\n}"
			+ "\n"
			+ "\n//INSTANCE means saturated"
			+ "\nI = INSTANCE {"
			+ "\n variables"
			+ "\n  v1: unitcode,"
			+ "\n  v2: unitcode,"
			+ "\n  v3: unitcode,"
			+ "\n  v4: unitcode,"
			+ "\n  v0: unitcode,"
			+ "\n  v999: unitcode,"
			+ "\n  v1: productorservicecategory,"
			+ "\n  v2: productorservicecategory,"
			+ "\n  v3: productorservicecategory,"
			+ "\n  v4: productorservicecategory,"
			+ "\n  v6: productorservicecategory,"
			+ "\n  v7: productorservicecategory,"
			+ "\n  v8: productorservicecategory,"
			+ "\n  v9: productorservicecategory,"
			+ "\n  v10: productorservicecategory,"
			+ "\n  v12: productorservicecategory,"
			+ "\n  v13: productorservicecategory,"
			+ "\n  v14: productorservicecategory,"
			+ "\n  v15: productorservicecategory,"
			+ "\n  v16: productorservicecategory,"
			+ "\n  v17: productorservicecategory,"
			+ "\n  v18: productorservicecategory,"
			+ "\n  v19: productorservicecategory,"
			+ "\n  v20: productorservicecategory,"
			+ "\n  v2: equipmenttype,"
			+ "\n  v3: equipmenttype,"
			+ "\n  v1: equipmenttype,"
			+ "\n  v8: equipmenttype,"
			+ "\n  v7: equipmenttype,"
			+ "\n  v9: equipmenttype,"
			+ "\n  v4: equipmenttype,"
			+ "\n  v6: equipmenttype,"
			+ "\n  v5: equipmenttype,"
			+ "\n  v10: equipmenttype,"
			+ "\n  v1: industry,"
			+ "\n  v2: industry,"
			+ "\n  v6: industry,"
			+ "\n  v4: industry,"
			+ "\n  v7: industry,"
			+ "\n  v8: industry,"
			+ "\n  v9: industry,"
			+ "\n  v5: industry,"
			+ "\n  v10: industry,"
			+ "\n  v11: industry,"
			+ "\n  v12: industry,"
			+ "\n  v13: industry,"
			+ "\n  v3: industry,"
			+ "\n  v14: industry,"
			+ "\n  v15: industry,"
			+ "\n  v16: industry,"
			+ "\n  v17: industry,"
			+ "\n  v1: material,"
			+ "\n  v2: material,"
			+ "\n  v3: material,"
			+ "\n  v4: material,"
			+ "\n  v5: material,"
			+ "\n  v6: material,"
			+ "\n  v7: material,"
			+ "\n  v8: material,"
			+ "\n  v9: material,"
			+ "\n  v10: material,"
			+ "\n  v11: material,"
			+ "\n  v12: material,"
			+ "\n  v13: material,"
			+ "\n  v14: material,"
			+ "\n  v15: material,"
			+ "\n  v16: material,"
			+ "\n  v17: material,"
			+ "\n  v18: material,"
			+ "\n  v19: material,"
			+ "\n  v20: material,"
			+ "\n  v21: material,"
			+ "\n  v22: material,"
			+ "\n  v23: material,"
			+ "\n  v24: material,"
			+ "\n  v25: material,"
			+ "\n  v26: material,"
			+ "\n  v27: material,"
			+ "\n  v28: material,"
			+ "\n  v29: material,"
			+ "\n  v30: material,"
			+ "\n  v31: material,"
			+ "\n  v32: material,"
			+ "\n  v33: material,"
			+ "\n  v34: material,"
			+ "\n  v35: material,"
			+ "\n  v36: material,"
			+ "\n  v37: material,"
			+ "\n  v38: material,"
			+ "\n  v39: material,"
			+ "\n  v40: material,"
			+ "\n  v41: material,"
			+ "\n  v1: moldtypes,"
			+ "\n  v7: moldtypes,"
			+ "\n  v8: moldtypes,"
			+ "\n  v2: moldtypes,"
			+ "\n  v3: moldtypes,"
			+ "\n  v4: moldtypes,"
			+ "\n  v9: moldtypes,"
			+ "\n  v5: moldtypes,"
			+ "\n  v6: moldtypes,"
			+ "\n  v1: process,"
			+ "\n  v2: process,"
			+ "\n  v3: process,"
			+ "\n  v4: process,"
			+ "\n  v5: process,"
			+ "\n  v6: process,"
			+ "\n  v7: process,"
			+ "\n  v1: supplier,"
			+ "\n  v2: supplier,"
			+ "\n  v3: supplier,"
			+ "\n  v4: supplier,"
			+ "\n  v5: supplier,"
			+ "\n  v6: supplier,"
			+ "\n  v7: supplier,"
			+ "\n  v8: supplier,"
			+ "\n  v1: capability,"
			+ "\n  v2: capability,"
			+ "\n  v3: capability,"
			+ "\n  v4: capability,"
			+ "\n  v5: capability,"
			+ "\n  v6: capability,"
			+ "\n  v7: capability,"
			+ "\n  v8: capability,"
			+ "\n  v9: capability,"
			+ "\n  v10: capability,"
			+ "\n  v11: capability,"
			+ "\n  v1: capabilitycategories,"
			+ "\n  v2: capabilitycategories,"
			+ "\n  v3: capabilitycategories,"
			+ "\n  v4: capabilitycategories,"
			+ "\n  v5: capabilitycategories,"
			+ "\n  v6: capabilitycategories,"
			+ "\n  v7: capabilitycategories,"
			+ "\n  v8: capabilitycategories,"
			+ "\n  v9: capabilitycategories,"
			+ "\n  v10: capabilitycategories,"
			+ "\n  v11: capabilitycategories,"
			+ "\n  v12: capabilitycategories,"
			+ "\n  v13: capabilitycategories,"
			+ "\n  v14: capabilitycategories,"
			+ "\n  v15: capabilitycategories,"
			+ "\n  v16: capabilitycategories,"
			+ "\n  v17: capabilitycategories,"
			+ "\n  v18: capabilitycategories,"
			+ "\n  v19: capabilitycategories,"
			+ "\n  v1: capabilityequipment,"
			+ "\n  v2: capabilityequipment,"
			+ "\n  v3: capabilityequipment,"
			+ "\n  v4: capabilityequipment,"
			+ "\n  v5: capabilityequipment,"
			+ "\n  v7: capabilityequipment,"
			+ "\n  v8: capabilityequipment,"
			+ "\n  v9: capabilityequipment,"
			+ "\n  v10: capabilityequipment,"
			+ "\n  v11: capabilityequipment,"
			+ "\n  v12: capabilityequipment,"
			+ "\n  v13: capabilityequipment,"
			+ "\n  v16: capabilityequipment,"
			+ "\n  v17: capabilityequipment,"
			+ "\n  v1: capabilityindustry,"
			+ "\n  v2: capabilityindustry,"
			+ "\n  v3: capabilityindustry,"
			+ "\n  v4: capabilityindustry,"
			+ "\n  v5: capabilityindustry,"
			+ "\n  v6: capabilityindustry,"
			+ "\n  v7: capabilityindustry,"
			+ "\n  v8: capabilityindustry,"
			+ "\n  v9: capabilityindustry,"
			+ "\n  v10: capabilityindustry,"
			+ "\n  v11: capabilityindustry,"
			+ "\n  v12: capabilityindustry,"
			+ "\n  v13: capabilityindustry,"
			+ "\n  v14: capabilityindustry,"
			+ "\n  v15: capabilityindustry,"
			+ "\n  v16: capabilityindustry,"
			+ "\n  v17: capabilityindustry,"
			+ "\n  v18: capabilityindustry,"
			+ "\n  v19: capabilityindustry,"
			+ "\n  v20: capabilityindustry,"
			+ "\n  v21: capabilityindustry,"
			+ "\n  v22: capabilityindustry,"
			+ "\n  v23: capabilityindustry,"
			+ "\n  v24: capabilityindustry,"
			+ "\n  v1: capabilitymaterials,"
			+ "\n  v2: capabilitymaterials,"
			+ "\n  v3: capabilitymaterials,"
			+ "\n  v4: capabilitymaterials,"
			+ "\n  v5: capabilitymaterials,"
			+ "\n  v6: capabilitymaterials,"
			+ "\n  v7: capabilitymaterials,"
			+ "\n  v8: capabilitymaterials,"
			+ "\n  v9: capabilitymaterials,"
			+ "\n  v10: capabilitymaterials,"
			+ "\n  v11: capabilitymaterials,"
			+ "\n  v12: capabilitymaterials,"
			+ "\n  v13: capabilitymaterials,"
			+ "\n  v14: capabilitymaterials,"
			+ "\n  v15: capabilitymaterials,"
			+ "\n  v16: capabilitymaterials,"
			+ "\n  v17: capabilitymaterials,"
			+ "\n  v18: capabilitymaterials,"
			+ "\n  v19: capabilitymaterials,"
			+ "\n  v20: capabilitymaterials,"
			+ "\n  v21: capabilitymaterials,"
			+ "\n  v22: capabilitymaterials,"
			+ "\n  v23: capabilitymaterials,"
			+ "\n  v24: capabilitymaterials,"
			+ "\n  v25: capabilitymaterials,"
			+ "\n  v26: capabilitymaterials,"
			+ "\n  v27: capabilitymaterials,"
			+ "\n  v28: capabilitymaterials,"
			+ "\n  v29: capabilitymaterials,"
			+ "\n  v30: capabilitymaterials,"
			+ "\n  v31: capabilitymaterials,"
			+ "\n  v32: capabilitymaterials,"
			+ "\n  v33: capabilitymaterials,"
			+ "\n  v34: capabilitymaterials,"
			+ "\n  v35: capabilitymaterials,"
			+ "\n  v36: capabilitymaterials,"
			+ "\n  v37: capabilitymaterials,"
			+ "\n  v38: capabilitymaterials,"
			+ "\n  v40: capabilitymaterials,"
			+ "\n  v41: capabilitymaterials,"
			+ "\n  v42: capabilitymaterials,"
			+ "\n  v43: capabilitymaterials,"
			+ "\n  v44: capabilitymaterials,"
			+ "\n  v45: capabilitymaterials,"
			+ "\n  v46: capabilitymaterials,"
			+ "\n  v47: capabilitymaterials,"
			+ "\n  v48: capabilitymaterials,"
			+ "\n  v49: capabilitymaterials,"
			+ "\n  v50: capabilitymaterials,"
			+ "\n  v51: capabilitymaterials,"
			+ "\n  v52: capabilitymaterials,"
			+ "\n  v53: capabilitymaterials,"
			+ "\n  v55: capabilitymaterials,"
			+ "\n  v56: capabilitymaterials,"
			+ "\n  v57: capabilitymaterials,"
			+ "\n  v58: capabilitymaterials,"
			+ "\n  v59: capabilitymaterials,"
			+ "\n  v60: capabilitymaterials,"
			+ "\n  v61: capabilitymaterials,"
			+ "\n  v62: capabilitymaterials,"
			+ "\n  v63: capabilitymaterials,"
			+ "\n  v64: capabilitymaterials,"
			+ "\n  v65: capabilitymaterials,"
			+ "\n  v66: capabilitymaterials,"
			+ "\n  v67: capabilitymaterials,"
			+ "\n  v68: capabilitymaterials,"
			+ "\n  v69: capabilitymaterials,"
			+ "\n  v70: capabilitymaterials,"
			+ "\n  v71: capabilitymaterials,"
			+ "\n  v72: capabilitymaterials,"
			+ "\n  v73: capabilitymaterials,"
			+ "\n  v74: capabilitymaterials,"
			+ "\n  v75: capabilitymaterials,"
			+ "\n  v76: capabilitymaterials,"
			+ "\n  v77: capabilitymaterials,"
			+ "\n  v78: capabilitymaterials,"
			+ "\n  v79: capabilitymaterials,"
			+ "\n  v80: capabilitymaterials,"
			+ "\n  v81: capabilitymaterials,"
			+ "\n  v82: capabilitymaterials,"
			+ "\n  v83: capabilitymaterials,"
			+ "\n  v85: capabilitymaterials,"
			+ "\n  v86: capabilitymaterials,"
			+ "\n  v87: capabilitymaterials,"
			+ "\n  v88: capabilitymaterials,"
			+ "\n  v1: capabilityprocesses,"
			+ "\n  v2: capabilityprocesses,"
			+ "\n  v3: capabilityprocesses,"
			+ "\n  v4: capabilityprocesses,"
			+ "\n  v5: capabilityprocesses,"
			+ "\n  v6: capabilityprocesses,"
			+ "\n  v7: capabilityprocesses,"
			+ "\n  v8: capabilityprocesses,"
			+ "\n  v9: capabilityprocesses,"
			+ "\n  v10: capabilityprocesses,"
			+ "\n  v11: capabilityprocesses,"
			+ "\n  v12: capabilityprocesses,"
			+ "\n  v13: capabilityprocesses,"
			+ "\n  v14: capabilityprocesses,"
			+ "\n  v15: capabilityprocesses,"
			+ "\n  v16: capabilityprocesses,"
			+ "\n  v18: capabilityprocesses,"
			+ "\n  v19: capabilityprocesses,"
			+ "\n  v20: capabilityprocesses,"
			+ "\n  v1: capabilitytypesofmolds,"
			+ "\n  v2: capabilitytypesofmolds,"
			+ "\n  v3: capabilitytypesofmolds,"
			+ "\n  v4: capabilitytypesofmolds,"
			+ "\n  v5: capabilitytypesofmolds,"
			+ "\n  v6: capabilitytypesofmolds,"
			+ "\n  v7: capabilitytypesofmolds,"
			+ "\n  v8: capabilitytypesofmolds,"
			+ "\n  v9: capabilitytypesofmolds,"
			+ "\n  v10: capabilitytypesofmolds,"
			+ "\n  v11: capabilitytypesofmolds,"
			+ "\n  v1: suppliercapabilities,"
			+ "\n  v2: suppliercapabilities,"
			+ "\n  v3: suppliercapabilities,"
			+ "\n  v4: suppliercapabilities,"
			+ "\n  v5: suppliercapabilities,"
			+ "\n  v6: suppliercapabilities,"
			+ "\n  v7: suppliercapabilities,"
			+ "\n  v8: suppliercapabilities,"
			+ "\n  v9: suppliercapabilities,"
			+ "\n  v10: suppliercapabilities,"
			+ "\n  v11: suppliercapabilities;"
			+ "\n equations"
			+ "\n  v1.productorservicecategory_Parent_id = v1,"
			+ "\n  v2.productorservicecategory_Parent_id = v1,"
			+ "\n  v3.productorservicecategory_Parent_id = v2,"
			+ "\n  v4.productorservicecategory_Parent_id = v3,"
			+ "\n  v6.productorservicecategory_Parent_id = v13,"
			+ "\n  v7.productorservicecategory_Parent_id = v13,"
			+ "\n  v8.productorservicecategory_Parent_id = v8,"
			+ "\n  v9.productorservicecategory_Parent_id = v8,"
			+ "\n  v10.productorservicecategory_Parent_id = v9,"
			+ "\n  v12.productorservicecategory_Parent_id = v2,"
			+ "\n  v13.productorservicecategory_Parent_id = v2,"
			+ "\n  v14.productorservicecategory_Parent_id = v13,"
			+ "\n  v15.productorservicecategory_Parent_id = v13,"
			+ "\n  v16.productorservicecategory_Parent_id = v13,"
			+ "\n  v17.productorservicecategory_Parent_id = v13,"
			+ "\n  v18.productorservicecategory_Parent_id = v9,"
			+ "\n  v19.productorservicecategory_Parent_id = v9,"
			+ "\n  v20.productorservicecategory_Parent_id = v9,"
			+ "\n  v1.capability_Parent_id = v1,"
			+ "\n  v2.capability_Parent_id = v2,"
			+ "\n  v3.capability_Parent_id = v5,"
			+ "\n  v4.capability_Parent_id = v5,"
			+ "\n  v5.capability_Parent_id = v5,"
			+ "\n  v6.capability_Parent_id = v6,"
			+ "\n  v7.capability_Parent_id = v7,"
			+ "\n  v8.capability_Parent_id = v8,"
			+ "\n  v9.capability_Parent_id = v9,"
			+ "\n  v10.capability_Parent_id = v10,"
			+ "\n  v11.capability_Parent_id = v11,"
			+ "\n  v1.capability_Production_Volume_Min_Unit = v0,"
			+ "\n  v2.capability_Production_Volume_Min_Unit = v1,"
			+ "\n  v3.capability_Production_Volume_Min_Unit = v0,"
			+ "\n  v4.capability_Production_Volume_Min_Unit = v0,"
			+ "\n  v5.capability_Production_Volume_Min_Unit = v0,"
			+ "\n  v6.capability_Production_Volume_Min_Unit = v1,"
			+ "\n  v7.capability_Production_Volume_Min_Unit = v1,"
			+ "\n  v8.capability_Production_Volume_Min_Unit = v0,"
			+ "\n  v9.capability_Production_Volume_Min_Unit = v0,"
			+ "\n  v10.capability_Production_Volume_Min_Unit = v0,"
			+ "\n  v11.capability_Production_Volume_Min_Unit = v0,"
			+ "\n  v1.capability_Production_Volume_Max_Unit = v0,"
			+ "\n  v2.capability_Production_Volume_Max_Unit = v2,"
			+ "\n  v3.capability_Production_Volume_Max_Unit = v0,"
			+ "\n  v4.capability_Production_Volume_Max_Unit = v0,"
			+ "\n  v5.capability_Production_Volume_Max_Unit = v0,"
			+ "\n  v6.capability_Production_Volume_Max_Unit = v1,"
			+ "\n  v7.capability_Production_Volume_Max_Unit = v1,"
			+ "\n  v8.capability_Production_Volume_Max_Unit = v0,"
			+ "\n  v9.capability_Production_Volume_Max_Unit = v0,"
			+ "\n  v10.capability_Production_Volume_Max_Unit = v0,"
			+ "\n  v11.capability_Production_Volume_Max_Unit = v0,"
			+ "\n  v1.capability_Max_Length_Unit = v999,"
			+ "\n  v2.capability_Max_Length_Unit = v0,"
			+ "\n  v3.capability_Max_Length_Unit = v3,"
			+ "\n  v4.capability_Max_Length_Unit = v3,"
			+ "\n  v5.capability_Max_Length_Unit = v0,"
			+ "\n  v6.capability_Max_Length_Unit = v3,"
			+ "\n  v7.capability_Max_Length_Unit = v3,"
			+ "\n  v8.capability_Max_Length_Unit = v0,"
			+ "\n  v9.capability_Max_Length_Unit = v0,"
			+ "\n  v10.capability_Max_Length_Unit = v0,"
			+ "\n  v11.capability_Max_Length_Unit = v0,"
			+ "\n  v1.capability_Tolerance_Unit = v0,"
			+ "\n  v2.capability_Tolerance_Unit = v0,"
			+ "\n  v3.capability_Tolerance_Unit = v3,"
			+ "\n  v4.capability_Tolerance_Unit = v3,"
			+ "\n  v5.capability_Tolerance_Unit = v0,"
			+ "\n  v6.capability_Tolerance_Unit = v4,"
			+ "\n  v7.capability_Tolerance_Unit = v3,"
			+ "\n  v8.capability_Tolerance_Unit = v0,"
			+ "\n  v9.capability_Tolerance_Unit = v0,"
			+ "\n  v10.capability_Tolerance_Unit = v0,"
			+ "\n  v11.capability_Tolerance_Unit = v0,"
			+ "\n  v1.capabilitycategories_Capability_id = v1,"
			+ "\n  v2.capabilitycategories_Capability_id = v1,"
			+ "\n  v3.capabilitycategories_Capability_id = v2,"
			+ "\n  v4.capabilitycategories_Capability_id = v2,"
			+ "\n  v5.capabilitycategories_Capability_id = v3,"
			+ "\n  v6.capabilitycategories_Capability_id = v4,"
			+ "\n  v7.capabilitycategories_Capability_id = v5,"
			+ "\n  v8.capabilitycategories_Capability_id = v6,"
			+ "\n  v9.capabilitycategories_Capability_id = v6,"
			+ "\n  v10.capabilitycategories_Capability_id = v6,"
			+ "\n  v11.capabilitycategories_Capability_id = v7,"
			+ "\n  v12.capabilitycategories_Capability_id = v7,"
			+ "\n  v13.capabilitycategories_Capability_id = v7,"
			+ "\n  v14.capabilitycategories_Capability_id = v7,"
			+ "\n  v15.capabilitycategories_Capability_id = v2,"
			+ "\n  v16.capabilitycategories_Capability_id = v8,"
			+ "\n  v17.capabilitycategories_Capability_id = v9,"
			+ "\n  v18.capabilitycategories_Capability_id = v10,"
			+ "\n  v19.capabilitycategories_Capability_id = v11,"
			+ "\n  v1.capabilitycategories_ProductOrServiceCategory_id = v6,"
			+ "\n  v2.capabilitycategories_ProductOrServiceCategory_id = v12,"
			+ "\n  v3.capabilitycategories_ProductOrServiceCategory_id = v6,"
			+ "\n  v4.capabilitycategories_ProductOrServiceCategory_id = v12,"
			+ "\n  v5.capabilitycategories_ProductOrServiceCategory_id = v6,"
			+ "\n  v6.capabilitycategories_ProductOrServiceCategory_id = v14,"
			+ "\n  v7.capabilitycategories_ProductOrServiceCategory_id = v13,"
			+ "\n  v8.capabilitycategories_ProductOrServiceCategory_id = v6,"
			+ "\n  v9.capabilitycategories_ProductOrServiceCategory_id = v7,"
			+ "\n  v10.capabilitycategories_ProductOrServiceCategory_id = v13,"
			+ "\n  v11.capabilitycategories_ProductOrServiceCategory_id = v6,"
			+ "\n  v12.capabilitycategories_ProductOrServiceCategory_id = v7,"
			+ "\n  v13.capabilitycategories_ProductOrServiceCategory_id = v15,"
			+ "\n  v14.capabilitycategories_ProductOrServiceCategory_id = v14,"
			+ "\n  v15.capabilitycategories_ProductOrServiceCategory_id = v14,"
			+ "\n  v16.capabilitycategories_ProductOrServiceCategory_id = v10,"
			+ "\n  v17.capabilitycategories_ProductOrServiceCategory_id = v10,"
			+ "\n  v18.capabilitycategories_ProductOrServiceCategory_id = v10,"
			+ "\n  v19.capabilitycategories_ProductOrServiceCategory_id = v10,"
			+ "\n  v1.capabilityequipment_Capability_id = v8,"
			+ "\n  v2.capabilityequipment_Capability_id = v8,"
			+ "\n  v3.capabilityequipment_Capability_id = v9,"
			+ "\n  v4.capabilityequipment_Capability_id = v9,"
			+ "\n  v5.capabilityequipment_Capability_id = v9,"
			+ "\n  v7.capabilityequipment_Capability_id = v10,"
			+ "\n  v8.capabilityequipment_Capability_id = v10,"
			+ "\n  v9.capabilityequipment_Capability_id = v10,"
			+ "\n  v10.capabilityequipment_Capability_id = v10,"
			+ "\n  v11.capabilityequipment_Capability_id = v10,"
			+ "\n  v12.capabilityequipment_Capability_id = v10,"
			+ "\n  v13.capabilityequipment_Capability_id = v10,"
			+ "\n  v16.capabilityequipment_Capability_id = v11,"
			+ "\n  v17.capabilityequipment_Capability_id = v11,"
			+ "\n  v1.capabilityequipment_EquipmentType_id = v2,"
			+ "\n  v2.capabilityequipment_EquipmentType_id = v3,"
			+ "\n  v3.capabilityequipment_EquipmentType_id = v2,"
			+ "\n  v4.capabilityequipment_EquipmentType_id = v3,"
			+ "\n  v5.capabilityequipment_EquipmentType_id = v1,"
			+ "\n  v7.capabilityequipment_EquipmentType_id = v4,"
			+ "\n  v8.capabilityequipment_EquipmentType_id = v5,"
			+ "\n  v9.capabilityequipment_EquipmentType_id = v6,"
			+ "\n  v10.capabilityequipment_EquipmentType_id = v7,"
			+ "\n  v11.capabilityequipment_EquipmentType_id = v8,"
			+ "\n  v12.capabilityequipment_EquipmentType_id = v10,"
			+ "\n  v13.capabilityequipment_EquipmentType_id = v9,"
			+ "\n  v16.capabilityequipment_EquipmentType_id = v10,"
			+ "\n  v17.capabilityequipment_EquipmentType_id = v1,"
			+ "\n  v1.capabilityindustry_Capability_id = v8,"
			+ "\n  v2.capabilityindustry_Capability_id = v8,"
			+ "\n  v3.capabilityindustry_Capability_id = v8,"
			+ "\n  v4.capabilityindustry_Capability_id = v8,"
			+ "\n  v5.capabilityindustry_Capability_id = v8,"
			+ "\n  v6.capabilityindustry_Capability_id = v9,"
			+ "\n  v7.capabilityindustry_Capability_id = v9,"
			+ "\n  v8.capabilityindustry_Capability_id = v9,"
			+ "\n  v9.capabilityindustry_Capability_id = v9,"
			+ "\n  v10.capabilityindustry_Capability_id = v9,"
			+ "\n  v11.capabilityindustry_Capability_id = v11,"
			+ "\n  v12.capabilityindustry_Capability_id = v11,"
			+ "\n  v13.capabilityindustry_Capability_id = v11,"
			+ "\n  v14.capabilityindustry_Capability_id = v11,"
			+ "\n  v15.capabilityindustry_Capability_id = v11,"
			+ "\n  v16.capabilityindustry_Capability_id = v11,"
			+ "\n  v17.capabilityindustry_Capability_id = v11,"
			+ "\n  v18.capabilityindustry_Capability_id = v11,"
			+ "\n  v19.capabilityindustry_Capability_id = v11,"
			+ "\n  v20.capabilityindustry_Capability_id = v11,"
			+ "\n  v21.capabilityindustry_Capability_id = v11,"
			+ "\n  v22.capabilityindustry_Capability_id = v11,"
			+ "\n  v23.capabilityindustry_Capability_id = v11,"
			+ "\n  v24.capabilityindustry_Capability_id = v11,"
			+ "\n  v1.capabilityindustry_Industry_id = v1,"
			+ "\n  v2.capabilityindustry_Industry_id = v2,"
			+ "\n  v3.capabilityindustry_Industry_id = v3,"
			+ "\n  v4.capabilityindustry_Industry_id = v4,"
			+ "\n  v5.capabilityindustry_Industry_id = v5,"
			+ "\n  v6.capabilityindustry_Industry_id = v1,"
			+ "\n  v7.capabilityindustry_Industry_id = v2,"
			+ "\n  v8.capabilityindustry_Industry_id = v3,"
			+ "\n  v9.capabilityindustry_Industry_id = v5,"
			+ "\n  v10.capabilityindustry_Industry_id = v4,"
			+ "\n  v11.capabilityindustry_Industry_id = v1,"
			+ "\n  v12.capabilityindustry_Industry_id = v6,"
			+ "\n  v13.capabilityindustry_Industry_id = v7,"
			+ "\n  v14.capabilityindustry_Industry_id = v8,"
			+ "\n  v15.capabilityindustry_Industry_id = v9,"
			+ "\n  v16.capabilityindustry_Industry_id = v10,"
			+ "\n  v17.capabilityindustry_Industry_id = v11,"
			+ "\n  v18.capabilityindustry_Industry_id = v12,"
			+ "\n  v19.capabilityindustry_Industry_id = v13,"
			+ "\n  v20.capabilityindustry_Industry_id = v3,"
			+ "\n  v21.capabilityindustry_Industry_id = v14,"
			+ "\n  v22.capabilityindustry_Industry_id = v15,"
			+ "\n  v23.capabilityindustry_Industry_id = v16,"
			+ "\n  v24.capabilityindustry_Industry_id = v17,"
			+ "\n  v1.capabilitymaterials_Capability_id = v1,"
			+ "\n  v2.capabilitymaterials_Capability_id = v1,"
			+ "\n  v3.capabilitymaterials_Capability_id = v1,"
			+ "\n  v4.capabilitymaterials_Capability_id = v1,"
			+ "\n  v5.capabilitymaterials_Capability_id = v1,"
			+ "\n  v6.capabilitymaterials_Capability_id = v1,"
			+ "\n  v7.capabilitymaterials_Capability_id = v1,"
			+ "\n  v8.capabilitymaterials_Capability_id = v1,"
			+ "\n  v9.capabilitymaterials_Capability_id = v2,"
			+ "\n  v10.capabilitymaterials_Capability_id = v2,"
			+ "\n  v11.capabilitymaterials_Capability_id = v2,"
			+ "\n  v12.capabilitymaterials_Capability_id = v2,"
			+ "\n  v13.capabilitymaterials_Capability_id = v2,"
			+ "\n  v14.capabilitymaterials_Capability_id = v2,"
			+ "\n  v15.capabilitymaterials_Capability_id = v2,"
			+ "\n  v16.capabilitymaterials_Capability_id = v2,"
			+ "\n  v17.capabilitymaterials_Capability_id = v3,"
			+ "\n  v18.capabilitymaterials_Capability_id = v3,"
			+ "\n  v19.capabilitymaterials_Capability_id = v3,"
			+ "\n  v20.capabilitymaterials_Capability_id = v3,"
			+ "\n  v21.capabilitymaterials_Capability_id = v3,"
			+ "\n  v22.capabilitymaterials_Capability_id = v3,"
			+ "\n  v23.capabilitymaterials_Capability_id = v3,"
			+ "\n  v24.capabilitymaterials_Capability_id = v3,"
			+ "\n  v25.capabilitymaterials_Capability_id = v3,"
			+ "\n  v26.capabilitymaterials_Capability_id = v3,"
			+ "\n  v27.capabilitymaterials_Capability_id = v3,"
			+ "\n  v28.capabilitymaterials_Capability_id = v4,"
			+ "\n  v29.capabilitymaterials_Capability_id = v4,"
			+ "\n  v30.capabilitymaterials_Capability_id = v4,"
			+ "\n  v31.capabilitymaterials_Capability_id = v4,"
			+ "\n  v32.capabilitymaterials_Capability_id = v4,"
			+ "\n  v33.capabilitymaterials_Capability_id = v4,"
			+ "\n  v34.capabilitymaterials_Capability_id = v4,"
			+ "\n  v35.capabilitymaterials_Capability_id = v4,"
			+ "\n  v36.capabilitymaterials_Capability_id = v4,"
			+ "\n  v37.capabilitymaterials_Capability_id = v4,"
			+ "\n  v38.capabilitymaterials_Capability_id = v4,"
			+ "\n  v40.capabilitymaterials_Capability_id = v6,"
			+ "\n  v41.capabilitymaterials_Capability_id = v6,"
			+ "\n  v42.capabilitymaterials_Capability_id = v6,"
			+ "\n  v43.capabilitymaterials_Capability_id = v6,"
			+ "\n  v44.capabilitymaterials_Capability_id = v6,"
			+ "\n  v45.capabilitymaterials_Capability_id = v6,"
			+ "\n  v46.capabilitymaterials_Capability_id = v7,"
			+ "\n  v47.capabilitymaterials_Capability_id = v7,"
			+ "\n  v48.capabilitymaterials_Capability_id = v7,"
			+ "\n  v49.capabilitymaterials_Capability_id = v7,"
			+ "\n  v50.capabilitymaterials_Capability_id = v7,"
			+ "\n  v51.capabilitymaterials_Capability_id = v7,"
			+ "\n  v52.capabilitymaterials_Capability_id = v7,"
			+ "\n  v53.capabilitymaterials_Capability_id = v2,"
			+ "\n  v55.capabilitymaterials_Capability_id = v8,"
			+ "\n  v56.capabilitymaterials_Capability_id = v8,"
			+ "\n  v57.capabilitymaterials_Capability_id = v8,"
			+ "\n  v58.capabilitymaterials_Capability_id = v8,"
			+ "\n  v59.capabilitymaterials_Capability_id = v8,"
			+ "\n  v60.capabilitymaterials_Capability_id = v8,"
			+ "\n  v61.capabilitymaterials_Capability_id = v8,"
			+ "\n  v62.capabilitymaterials_Capability_id = v8,"
			+ "\n  v63.capabilitymaterials_Capability_id = v8,"
			+ "\n  v64.capabilitymaterials_Capability_id = v8,"
			+ "\n  v65.capabilitymaterials_Capability_id = v8,"
			+ "\n  v66.capabilitymaterials_Capability_id = v8,"
			+ "\n  v67.capabilitymaterials_Capability_id = v8,"
			+ "\n  v68.capabilitymaterials_Capability_id = v8,"
			+ "\n  v69.capabilitymaterials_Capability_id = v9,"
			+ "\n  v70.capabilitymaterials_Capability_id = v9,"
			+ "\n  v71.capabilitymaterials_Capability_id = v9,"
			+ "\n  v72.capabilitymaterials_Capability_id = v9,"
			+ "\n  v73.capabilitymaterials_Capability_id = v9,"
			+ "\n  v74.capabilitymaterials_Capability_id = v9,"
			+ "\n  v75.capabilitymaterials_Capability_id = v9,"
			+ "\n  v76.capabilitymaterials_Capability_id = v9,"
			+ "\n  v77.capabilitymaterials_Capability_id = v9,"
			+ "\n  v78.capabilitymaterials_Capability_id = v9,"
			+ "\n  v79.capabilitymaterials_Capability_id = v9,"
			+ "\n  v80.capabilitymaterials_Capability_id = v9,"
			+ "\n  v81.capabilitymaterials_Capability_id = v9,"
			+ "\n  v82.capabilitymaterials_Capability_id = v9,"
			+ "\n  v83.capabilitymaterials_Capability_id = v10,"
			+ "\n  v85.capabilitymaterials_Capability_id = v10,"
			+ "\n  v86.capabilitymaterials_Capability_id = v10,"
			+ "\n  v87.capabilitymaterials_Capability_id = v11,"
			+ "\n  v88.capabilitymaterials_Capability_id = v11,"
			+ "\n  v1.capabilitymaterials_Material_id = v1,"
			+ "\n  v2.capabilitymaterials_Material_id = v2,"
			+ "\n  v3.capabilitymaterials_Material_id = v3,"
			+ "\n  v4.capabilitymaterials_Material_id = v4,"
			+ "\n  v5.capabilitymaterials_Material_id = v5,"
			+ "\n  v6.capabilitymaterials_Material_id = v6,"
			+ "\n  v7.capabilitymaterials_Material_id = v7,"
			+ "\n  v8.capabilitymaterials_Material_id = v10,"
			+ "\n  v9.capabilitymaterials_Material_id = v4,"
			+ "\n  v10.capabilitymaterials_Material_id = v8,"
			+ "\n  v11.capabilitymaterials_Material_id = v12,"
			+ "\n  v12.capabilitymaterials_Material_id = v13,"
			+ "\n  v13.capabilitymaterials_Material_id = v14,"
			+ "\n  v14.capabilitymaterials_Material_id = v15,"
			+ "\n  v15.capabilitymaterials_Material_id = v16,"
			+ "\n  v16.capabilitymaterials_Material_id = v17,"
			+ "\n  v17.capabilitymaterials_Material_id = v18,"
			+ "\n  v18.capabilitymaterials_Material_id = v5,"
			+ "\n  v19.capabilitymaterials_Material_id = v6,"
			+ "\n  v20.capabilitymaterials_Material_id = v4,"
			+ "\n  v21.capabilitymaterials_Material_id = v8,"
			+ "\n  v22.capabilitymaterials_Material_id = v19,"
			+ "\n  v23.capabilitymaterials_Material_id = v20,"
			+ "\n  v24.capabilitymaterials_Material_id = v21,"
			+ "\n  v25.capabilitymaterials_Material_id = v22,"
			+ "\n  v26.capabilitymaterials_Material_id = v23,"
			+ "\n  v27.capabilitymaterials_Material_id = v24,"
			+ "\n  v28.capabilitymaterials_Material_id = v4,"
			+ "\n  v29.capabilitymaterials_Material_id = v5,"
			+ "\n  v30.capabilitymaterials_Material_id = v6,"
			+ "\n  v31.capabilitymaterials_Material_id = v8,"
			+ "\n  v32.capabilitymaterials_Material_id = v18,"
			+ "\n  v33.capabilitymaterials_Material_id = v19,"
			+ "\n  v34.capabilitymaterials_Material_id = v20,"
			+ "\n  v35.capabilitymaterials_Material_id = v21,"
			+ "\n  v36.capabilitymaterials_Material_id = v22,"
			+ "\n  v37.capabilitymaterials_Material_id = v23,"
			+ "\n  v38.capabilitymaterials_Material_id = v24,"
			+ "\n  v40.capabilitymaterials_Material_id = v25,"
			+ "\n  v41.capabilitymaterials_Material_id = v4,"
			+ "\n  v42.capabilitymaterials_Material_id = v8,"
			+ "\n  v43.capabilitymaterials_Material_id = v18,"
			+ "\n  v44.capabilitymaterials_Material_id = v9,"
			+ "\n  v45.capabilitymaterials_Material_id = v5,"
			+ "\n  v46.capabilitymaterials_Material_id = v25,"
			+ "\n  v47.capabilitymaterials_Material_id = v4,"
			+ "\n  v48.capabilitymaterials_Material_id = v8,"
			+ "\n  v49.capabilitymaterials_Material_id = v18,"
			+ "\n  v50.capabilitymaterials_Material_id = v5,"
			+ "\n  v51.capabilitymaterials_Material_id = v6,"
			+ "\n  v52.capabilitymaterials_Material_id = v9,"
			+ "\n  v53.capabilitymaterials_Material_id = v6,"
			+ "\n  v55.capabilitymaterials_Material_id = v2,"
			+ "\n  v56.capabilitymaterials_Material_id = v26,"
			+ "\n  v57.capabilitymaterials_Material_id = v27,"
			+ "\n  v58.capabilitymaterials_Material_id = v3,"
			+ "\n  v59.capabilitymaterials_Material_id = v28,"
			+ "\n  v60.capabilitymaterials_Material_id = v29,"
			+ "\n  v61.capabilitymaterials_Material_id = v30,"
			+ "\n  v62.capabilitymaterials_Material_id = v31,"
			+ "\n  v63.capabilitymaterials_Material_id = v32,"
			+ "\n  v64.capabilitymaterials_Material_id = v33,"
			+ "\n  v65.capabilitymaterials_Material_id = v34,"
			+ "\n  v66.capabilitymaterials_Material_id = v35,"
			+ "\n  v67.capabilitymaterials_Material_id = v36,"
			+ "\n  v68.capabilitymaterials_Material_id = v38,"
			+ "\n  v69.capabilitymaterials_Material_id = v2,"
			+ "\n  v70.capabilitymaterials_Material_id = v26,"
			+ "\n  v71.capabilitymaterials_Material_id = v27,"
			+ "\n  v72.capabilitymaterials_Material_id = v3,"
			+ "\n  v73.capabilitymaterials_Material_id = v28,"
			+ "\n  v74.capabilitymaterials_Material_id = v29,"
			+ "\n  v75.capabilitymaterials_Material_id = v30,"
			+ "\n  v76.capabilitymaterials_Material_id = v31,"
			+ "\n  v77.capabilitymaterials_Material_id = v32,"
			+ "\n  v78.capabilitymaterials_Material_id = v33,"
			+ "\n  v79.capabilitymaterials_Material_id = v34,"
			+ "\n  v80.capabilitymaterials_Material_id = v35,"
			+ "\n  v81.capabilitymaterials_Material_id = v36,"
			+ "\n  v82.capabilitymaterials_Material_id = v38,"
			+ "\n  v83.capabilitymaterials_Material_id = v4,"
			+ "\n  v85.capabilitymaterials_Material_id = v39,"
			+ "\n  v86.capabilitymaterials_Material_id = v40,"
			+ "\n  v87.capabilitymaterials_Material_id = v3,"
			+ "\n  v88.capabilitymaterials_Material_id = v41,"
			+ "\n  v1.capabilityprocesses_Capability_id = v1,"
			+ "\n  v2.capabilityprocesses_Capability_id = v1,"
			+ "\n  v3.capabilityprocesses_Capability_id = v2,"
			+ "\n  v4.capabilityprocesses_Capability_id = v2,"
			+ "\n  v5.capabilityprocesses_Capability_id = v2,"
			+ "\n  v6.capabilityprocesses_Capability_id = v2,"
			+ "\n  v7.capabilityprocesses_Capability_id = v3,"
			+ "\n  v8.capabilityprocesses_Capability_id = v3,"
			+ "\n  v9.capabilityprocesses_Capability_id = v3,"
			+ "\n  v10.capabilityprocesses_Capability_id = v4,"
			+ "\n  v11.capabilityprocesses_Capability_id = v4,"
			+ "\n  v12.capabilityprocesses_Capability_id = v4,"
			+ "\n  v13.capabilityprocesses_Capability_id = v6,"
			+ "\n  v14.capabilityprocesses_Capability_id = v6,"
			+ "\n  v15.capabilityprocesses_Capability_id = v6,"
			+ "\n  v16.capabilityprocesses_Capability_id = v7,"
			+ "\n  v18.capabilityprocesses_Capability_id = v7,"
			+ "\n  v19.capabilityprocesses_Capability_id = v7,"
			+ "\n  v20.capabilityprocesses_Capability_id = v7,"
			+ "\n  v1.capabilityprocesses_Process_id = v1,"
			+ "\n  v2.capabilityprocesses_Process_id = v2,"
			+ "\n  v3.capabilityprocesses_Process_id = v2,"
			+ "\n  v4.capabilityprocesses_Process_id = v1,"
			+ "\n  v5.capabilityprocesses_Process_id = v6,"
			+ "\n  v6.capabilityprocesses_Process_id = v7,"
			+ "\n  v7.capabilityprocesses_Process_id = v1,"
			+ "\n  v8.capabilityprocesses_Process_id = v2,"
			+ "\n  v9.capabilityprocesses_Process_id = v3,"
			+ "\n  v10.capabilityprocesses_Process_id = v1,"
			+ "\n  v11.capabilityprocesses_Process_id = v2,"
			+ "\n  v12.capabilityprocesses_Process_id = v3,"
			+ "\n  v13.capabilityprocesses_Process_id = v1,"
			+ "\n  v14.capabilityprocesses_Process_id = v2,"
			+ "\n  v15.capabilityprocesses_Process_id = v3,"
			+ "\n  v16.capabilityprocesses_Process_id = v2,"
			+ "\n  v18.capabilityprocesses_Process_id = v4,"
			+ "\n  v19.capabilityprocesses_Process_id = v5,"
			+ "\n  v20.capabilityprocesses_Process_id = v1,"
			+ "\n  v1.capabilitytypesofmolds_Capability_id = v10,"
			+ "\n  v2.capabilitytypesofmolds_Capability_id = v10,"
			+ "\n  v3.capabilitytypesofmolds_Capability_id = v10,"
			+ "\n  v4.capabilitytypesofmolds_Capability_id = v10,"
			+ "\n  v5.capabilitytypesofmolds_Capability_id = v10,"
			+ "\n  v6.capabilitytypesofmolds_Capability_id = v10,"
			+ "\n  v7.capabilitytypesofmolds_Capability_id = v11,"
			+ "\n  v8.capabilitytypesofmolds_Capability_id = v11,"
			+ "\n  v9.capabilitytypesofmolds_Capability_id = v11,"
			+ "\n  v10.capabilitytypesofmolds_Capability_id = v11,"
			+ "\n  v11.capabilitytypesofmolds_Capability_id = v11,"
			+ "\n  v1.capabilitytypesofmolds_MoldTypes_id = v1,"
			+ "\n  v2.capabilitytypesofmolds_MoldTypes_id = v2,"
			+ "\n  v3.capabilitytypesofmolds_MoldTypes_id = v3,"
			+ "\n  v4.capabilitytypesofmolds_MoldTypes_id = v4,"
			+ "\n  v5.capabilitytypesofmolds_MoldTypes_id = v5,"
			+ "\n  v6.capabilitytypesofmolds_MoldTypes_id = v6,"
			+ "\n  v7.capabilitytypesofmolds_MoldTypes_id = v1,"
			+ "\n  v8.capabilitytypesofmolds_MoldTypes_id = v7,"
			+ "\n  v9.capabilitytypesofmolds_MoldTypes_id = v8,"
			+ "\n  v10.capabilitytypesofmolds_MoldTypes_id = v2,"
			+ "\n  v11.capabilitytypesofmolds_MoldTypes_id = v9,"
			+ "\n  v1.suppliercapabilities_Supplier_id = v1,"
			+ "\n  v2.suppliercapabilities_Supplier_id = v1,"
			+ "\n  v3.suppliercapabilities_Supplier_id = v3,"
			+ "\n  v4.suppliercapabilities_Supplier_id = v3,"
			+ "\n  v5.suppliercapabilities_Supplier_id = v3,"
			+ "\n  v6.suppliercapabilities_Supplier_id = v4,"
			+ "\n  v7.suppliercapabilities_Supplier_id = v5,"
			+ "\n  v8.suppliercapabilities_Supplier_id = v6,"
			+ "\n  v9.suppliercapabilities_Supplier_id = v6,"
			+ "\n  v10.suppliercapabilities_Supplier_id = v7,"
			+ "\n  v11.suppliercapabilities_Supplier_id = v8,"
			+ "\n  v1.suppliercapabilities_Capability_id = v1,"
			+ "\n  v2.suppliercapabilities_Capability_id = v2,"
			+ "\n  v3.suppliercapabilities_Capability_id = v3,"
			+ "\n  v4.suppliercapabilities_Capability_id = v4,"
			+ "\n  v5.suppliercapabilities_Capability_id = v5,"
			+ "\n  v6.suppliercapabilities_Capability_id = v6,"
			+ "\n  v7.suppliercapabilities_Capability_id = v7,"
			+ "\n  v8.suppliercapabilities_Capability_id = v8,"
			+ "\n  v9.suppliercapabilities_Capability_id = v9,"
			+ "\n  v10.suppliercapabilities_Capability_id = v10,"
			+ "\n  v11.suppliercapabilities_Capability_id = v11,"
			+ "\n  v1.unitcode_Code = \"EA\","
			+ "\n  v2.unitcode_Code = \"Thousands\","
			+ "\n  v3.unitcode_Code = \"Inch\","
			+ "\n  v4.unitcode_Code = \"mm\","
			+ "\n  v0.unitcode_Code = \"NULL\","
			+ "\n  v999.unitcode_Code = \"NULL - WTF\","
			+ "\n  v1.unitcode_Description = \"Each part/piece count\","
			+ "\n  v2.unitcode_Description = \"1000 parts/pieces count\","
			+ "\n  v3.unitcode_Description = \"Length measure in inches\","
			+ "\n  v4.unitcode_Description = \"Length measure in millimeters\","
			+ "\n  v0.unitcode_Description = \"No unit\","
			+ "\n  v999.unitcode_Description = \"Possible error\","
			+ "\n  v1.productorservicecategory_Category_Name = \"Custom Manufacturing & Fabricating\","
			+ "\n  v2.productorservicecategory_Category_Name = \"Machining\","
			+ "\n  v3.productorservicecategory_Category_Name = \"General machining\","
			+ "\n  v4.productorservicecategory_Category_Name = \"Complex & Difficult Machining\","
			+ "\n  v6.productorservicecategory_Category_Name = \"Sinker EDM\","
			+ "\n  v7.productorservicecategory_Category_Name = \"Ram EDM\","
			+ "\n  v8.productorservicecategory_Category_Name = \"Machinery Tools & Supplies\","
			+ "\n  v9.productorservicecategory_Category_Name = \"Dies & Molds\","
			+ "\n  v10.productorservicecategory_Category_Name = \"Injection Molds\","
			+ "\n  v12.productorservicecategory_Category_Name = \"CNC Machining\","
			+ "\n  v13.productorservicecategory_Category_Name = \"EDM\","
			+ "\n  v14.productorservicecategory_Category_Name = \"Wire EDM\","
			+ "\n  v15.productorservicecategory_Category_Name = \"Small Hole EDM\","
			+ "\n  v16.productorservicecategory_Category_Name = \"Micro Hole EDM\","
			+ "\n  v17.productorservicecategory_Category_Name = \"High Speed Small Hole EDM\","
			+ "\n  v18.productorservicecategory_Category_Name = \"Forging Dies\","
			+ "\n  v19.productorservicecategory_Category_Name = \"Extrusion Dies\","
			+ "\n  v20.productorservicecategory_Category_Name = \"Rotary Dies\","
			+ "\n  v1.productorservicecategory_isLeaf = 0,"
			+ "\n  v2.productorservicecategory_isLeaf = 0,"
			+ "\n  v3.productorservicecategory_isLeaf = 0,"
			+ "\n  v4.productorservicecategory_isLeaf = 0,"
			+ "\n  v6.productorservicecategory_isLeaf = 1,"
			+ "\n  v7.productorservicecategory_isLeaf = 1,"
			+ "\n  v8.productorservicecategory_isLeaf = 0,"
			+ "\n  v9.productorservicecategory_isLeaf = 0,"
			+ "\n  v10.productorservicecategory_isLeaf = 1,"
			+ "\n  v12.productorservicecategory_isLeaf = 1,"
			+ "\n  v13.productorservicecategory_isLeaf = 1,"
			+ "\n  v14.productorservicecategory_isLeaf = 1,"
			+ "\n  v15.productorservicecategory_isLeaf = 1,"
			+ "\n  v16.productorservicecategory_isLeaf = 1,"
			+ "\n  v17.productorservicecategory_isLeaf = 1,"
			+ "\n  v18.productorservicecategory_isLeaf = 1,"
			+ "\n  v19.productorservicecategory_isLeaf = 1,"
			+ "\n  v20.productorservicecategory_isLeaf = 0,"
			+ "\n  v2.equipmenttype_EquipmentType_Name = \"CNC 3-axis Milling Machine\","
			+ "\n  v3.equipmenttype_EquipmentType_Name = \"CNC 4-axis Milling Machine\","
			+ "\n  v1.equipmenttype_EquipmentType_Name = \"EDM\","
			+ "\n  v8.equipmenttype_EquipmentType_Name = \"Engraving Machine\","
			+ "\n  v7.equipmenttype_EquipmentType_Name = \"Honing Machine\","
			+ "\n  v9.equipmenttype_EquipmentType_Name = \"Jig Grinder\","
			+ "\n  v4.equipmenttype_EquipmentType_Name = \"Lathe\","
			+ "\n  v6.equipmenttype_EquipmentType_Name = \"Sinker EDM\","
			+ "\n  v5.equipmenttype_EquipmentType_Name = \"Surface Grinder\","
			+ "\n  v10.equipmenttype_EquipmentType_Name = \"Verticle CNC Milling Machine\","
			+ "\n  v1.industry_Industry_Name = \"Aerospace\","
			+ "\n  v2.industry_Industry_Name = \"Automotive\","
			+ "\n  v6.industry_Industry_Name = \"Building/Construction\","
			+ "\n  v4.industry_Industry_Name = \"Commercial\","
			+ "\n  v7.industry_Industry_Name = \"Communication\","
			+ "\n  v8.industry_Industry_Name = \"Consumer Goods\","
			+ "\n  v9.industry_Industry_Name = \"Electrical\","
			+ "\n  v5.industry_Industry_Name = \"Electrical Connectors\","
			+ "\n  v10.industry_Industry_Name = \"Electronic\","
			+ "\n  v11.industry_Industry_Name = \"Food Processing\","
			+ "\n  v12.industry_Industry_Name = \"Industrial\","
			+ "\n  v13.industry_Industry_Name = \"Marine\","
			+ "\n  v3.industry_Industry_Name = \"Medical\","
			+ "\n  v14.industry_Industry_Name = \"Military/Government\","
			+ "\n  v15.industry_Industry_Name = \"Music\","
			+ "\n  v16.industry_Industry_Name = \"Optical\","
			+ "\n  v17.industry_Industry_Name = \"Recreational Vehicle\","
			+ "\n  v1.material_Material_Name = \"4140 Alloy Steels\","
			+ "\n  v2.material_Material_Name = \"A-2 Tool Steel\","
			+ "\n  v3.material_Material_Name = \"H-13 Tool Steel\","
			+ "\n  v4.material_Material_Name = \"Aluminum\","
			+ "\n  v5.material_Material_Name = \"Stainless Steel\","
			+ "\n  v6.material_Material_Name = \"Titanium\","
			+ "\n  v7.material_Material_Name = \"Tool Steel\","
			+ "\n  v8.material_Material_Name = \"Brass\","
			+ "\n  v9.material_Material_Name = \"Cobalt\","
			+ "\n  v10.material_Material_Name = \"A-6 Tool Steel\","
			+ "\n  v11.material_Material_Name = \"Chrome\","
			+ "\n  v12.material_Material_Name = \"Columbium\","
			+ "\n  v13.material_Material_Name = \"Stainless Steel 300 Series\","
			+ "\n  v14.material_Material_Name = \"Titanium Alloy Ti 6AI-4V\","
			+ "\n  v15.material_Material_Name = \"Titanium Alloy Ti 6AI-4V ELI\","
			+ "\n  v16.material_Material_Name = \"Titanium Alloy CP2\","
			+ "\n  v17.material_Material_Name = \"Titanium Alloy CP4\","
			+ "\n  v18.material_Material_Name = \"Carbon Steel\","
			+ "\n  v19.material_Material_Name = \"Plastics\","
			+ "\n  v20.material_Material_Name = \"Ferrous\","
			+ "\n  v21.material_Material_Name = \"Non-Ferrous\","
			+ "\n  v22.material_Material_Name = \"Castings\","
			+ "\n  v23.material_Material_Name = \"Forgings\","
			+ "\n  v24.material_Material_Name = \"Extrusions\","
			+ "\n  v25.material_Material_Name = \"Alloy Steel\","
			+ "\n  v26.material_Material_Name = \"S7 Tool Steel\","
			+ "\n  v27.material_Material_Name = \"M2 Tool Steel\","
			+ "\n  v28.material_Material_Name = \"D2 Tool Steel\","
			+ "\n  v29.material_Material_Name = \"4130 Tool Steel\","
			+ "\n  v30.material_Material_Name = \"Tool Steel 4340\","
			+ "\n  v31.material_Material_Name = \"300 Stainless Steel\","
			+ "\n  v32.material_Material_Name = \"Stainless Steel 302\","
			+ "\n  v33.material_Material_Name = \"304 Stainless Steel\","
			+ "\n  v34.material_Material_Name = \"316 Stainless Steel\","
			+ "\n  v35.material_Material_Name = \"15-4 Stainless Steel\","
			+ "\n  v36.material_Material_Name = \"17-4 Stainless Steel\","
			+ "\n  v37.material_Material_Name = \"Others\","
			+ "\n  v38.material_Material_Name = \"CR/HR Steel\","
			+ "\n  v39.material_Material_Name = \"Pre-hardened Steel\","
			+ "\n  v40.material_Material_Name = \"Fully Hardened Tool Steel\","
			+ "\n  v41.material_Material_Name = \"P-20\","
			+ "\n  v1.moldtypes_MoldTypes_Name = \"Blow Molds (Extrusion or Injection/Blow)\","
			+ "\n  v7.moldtypes_MoldTypes_Name = \"Collapsible Core\","
			+ "\n  v8.moldtypes_MoldTypes_Name = \"Die Cast Molds\","
			+ "\n  v2.moldtypes_MoldTypes_Name = \"Hot Runners\","
			+ "\n  v3.moldtypes_MoldTypes_Name = \"Inserts Only\","
			+ "\n  v4.moldtypes_MoldTypes_Name = \"Liquid Silicone Molds\","
			+ "\n  v9.moldtypes_MoldTypes_Name = \"Multi-Cavity/Family Injection Molds\","
			+ "\n  v5.moldtypes_MoldTypes_Name = \"Plastic Injection\","
			+ "\n  v6.moldtypes_MoldTypes_Name = \"Transfer/Compression (Rubber or Silicone)\","
			+ "\n  v1.process_Process_Name = \"Sinker EDM\","
			+ "\n  v2.process_Process_Name = \"Wire EDM\","
			+ "\n  v3.process_Process_Name = \"Small Hole EDM\","
			+ "\n  v4.process_Process_Name = \"EDM Drilling\","
			+ "\n  v5.process_Process_Name = \"Electrode Machining\","
			+ "\n  v6.process_Process_Name = \"Plunger EDM\","
			+ "\n  v7.process_Process_Name = \"Ram EDM\","
			+ "\n  v1.supplier_Source = \"B&B\","
			+ "\n  v2.supplier_Source = \"Tecomet\","
			+ "\n  v3.supplier_Source = \"Astro\","
			+ "\n  v4.supplier_Source = \"Bobs Design\","
			+ "\n  v5.supplier_Source = \"Wiegel Tool\","
			+ "\n  v6.supplier_Source = \"Industrial Tools & Die\","
			+ "\n  v7.supplier_Source = \"Pro Mold\","
			+ "\n  v8.supplier_Source = \"Klann Plastics and Canyon Plastics\","
			+ "\n  v1.supplier_Note = \"\","
			+ "\n  v2.supplier_Note = \"\","
			+ "\n  v3.supplier_Note = \"\","
			+ "\n  v4.supplier_Note = \"\","
			+ "\n  v5.supplier_Note = \"\","
			+ "\n  v6.supplier_Note = \"\","
			+ "\n  v7.supplier_Note = \"This supplier has another capability registered under the Injection Molds category, but it is more about molding rather than making the mold. So I excluded that. It also has a separate capability profile about mold design that I excluded.\","
			+ "\n  v8.supplier_Note = \"I used the types of molds values from the Canyon Plastics.\","
			+ "\n  v1.capability_Capability_Name = \"CNC Machining\","
			+ "\n  v2.capability_Capability_Name = \"CNC & Conventional Machining (turning & milling)\","
			+ "\n  v3.capability_Capability_Name = \"Sinker EDM\","
			+ "\n  v4.capability_Capability_Name = \"Wire EDM\","
			+ "\n  v5.capability_Capability_Name = \"EDM\","
			+ "\n  v6.capability_Capability_Name = \"Electrical Discharge Machining Services\","
			+ "\n  v7.capability_Capability_Name = \"Wire Electrical Discharge Machining\","
			+ "\n  v8.capability_Capability_Name = \"Custom  Molds for Plastic, Rubber, and Die Cast parts\","
			+ "\n  v9.capability_Capability_Name = \"Prototype and Production Mold Design & Manufacturing\","
			+ "\n  v10.capability_Capability_Name = \"Plastic Mold Making Services\","
			+ "\n  v11.capability_Capability_Name = \"Mold Design and Build\","
			+ "\n  v1.capability_Production_Volume_Min = \"NULL\","
			+ "\n  v2.capability_Production_Volume_Min = 1,"
			+ "\n  v3.capability_Production_Volume_Min = \"NULL\","
			+ "\n  v4.capability_Production_Volume_Min = \"NULL\","
			+ "\n  v5.capability_Production_Volume_Min = \"NULL\","
			+ "\n  v6.capability_Production_Volume_Min = 1,"
			+ "\n  v7.capability_Production_Volume_Min = 1,"
			+ "\n  v8.capability_Production_Volume_Min = \"NULL\","
			+ "\n  v9.capability_Production_Volume_Min = \"NULL\","
			+ "\n  v10.capability_Production_Volume_Min = \"NULL\","
			+ "\n  v11.capability_Production_Volume_Min = \"NULL\","
			+ "\n  v1.capability_Production_Volume_Max = \"NULL\","
			+ "\n  v2.capability_Production_Volume_Max = 1,"
			+ "\n  v3.capability_Production_Volume_Max = \"NULL\","
			+ "\n  v4.capability_Production_Volume_Max = \"NULL\","
			+ "\n  v5.capability_Production_Volume_Max = \"NULL\","
			+ "\n  v6.capability_Production_Volume_Max = 1000,"
			+ "\n  v7.capability_Production_Volume_Max = 1000000,"
			+ "\n  v8.capability_Production_Volume_Max = \"NULL\","
			+ "\n  v9.capability_Production_Volume_Max = \"NULL\","
			+ "\n  v10.capability_Production_Volume_Max = \"NULL\","
			+ "\n  v11.capability_Production_Volume_Max = \"NULL\","
			+ "\n  v1.capability_Max_Length = 40,"
			+ "\n  v2.capability_Max_Length = \"NULL\","
			+ "\n  v3.capability_Max_Length = \"47.25\","
			+ "\n  v4.capability_Max_Length = \"18.25\","
			+ "\n  v5.capability_Max_Length = \"NULL\","
			+ "\n  v6.capability_Max_Length = 20,"
			+ "\n  v7.capability_Max_Length = 20,"
			+ "\n  v8.capability_Max_Length = \"NULL\","
			+ "\n  v9.capability_Max_Length = \"NULL\","
			+ "\n  v10.capability_Max_Length = \"NULL\","
			+ "\n  v11.capability_Max_Length = \"NULL\","
			+ "\n  v1.capability_Tolerance = \"NULL\","
			+ "\n  v2.capability_Tolerance = \"NULL\","
			+ "\n  v3.capability_Tolerance = \"0.001\","
			+ "\n  v4.capability_Tolerance = \"0.005\","
			+ "\n  v5.capability_Tolerance = \"NULL\","
			+ "\n  v6.capability_Tolerance = \"0.0025\","
			+ "\n  v7.capability_Tolerance = \"0.000001\","
			+ "\n  v8.capability_Tolerance = \"NULL\","
			+ "\n  v9.capability_Tolerance = \"NULL\","
			+ "\n  v10.capability_Tolerance = \"NULL\","
			+ "\n  v11.capability_Tolerance = \"NULL\";"
			+ "\n} : S"
			+ "\n"
			+ "\n/////////////////////////////////////////////////////////////////"
			+ "\n"
			+ "\n//takes 30 minutes"
			+ "\n/*"
			+ "\nQ1_pre = flower { "
			+ "\n select"
			+ "\n  m.material_Material_Name as mn, "
			+ "\n  c.capability_Capability_Name as ccn,"
			+ "\n  c.capability_Max_Length as ml, "
			+ "\n  uc.unitcode_Code as ucc,"
			+ "\n  posc.productorservicecategory_Category_Name as pcn;"
			+ "\n from"
			+ "\n  productorservicecategory as posc,"
			+ "\n  material as m,"
			+ "\n  unitcode as uc,"
			+ "\n  capability as c,"
			+ "\n  capabilitymaterials as cmX,"
			+ "\n  capabilitycategories as cc;"
			+ "\n where"
			+ "\n  c = cmX.capabilitymaterials_Capability_id,"
			+ "\n  uc = c.capability_Max_Length_Unit,"
			+ "\n  m = cmX.capabilitymaterials_Material_id,"
			+ "\n  c = cc.capabilitycategories_Capability_id,"
			+ "\n  posc = cc.capabilitycategories_ProductOrServiceCategory_id;"
			+ "\n} I  "
			+ "\n*/"
			+ "\n"
			+ "\n//crashes GC after 1 hour"
			+ "\n/*"
			+ "\nQ1 = FLOWER { "
			+ "\n select"
			+ "\n  m.material_Material_Name as mn, "
			+ "\n  c.capability_Capability_Name as ccn,"
			+ "\n  c.capability_Max_Length as ml, "
			+ "\n  uc.unitcode_Code as ucc,"
			+ "\n  posc.productorservicecategory_Category_Name as pcn;"
			+ "\n from"
			+ "\n  productorservicecategory as posc,"
			+ "\n  material as m,"
			+ "\n  unitcode as uc,"
			+ "\n  capability as c,"
			+ "\n  capabilitymaterials as cmX,"
			+ "\n  capabilitycategories as cc;"
			+ "\n where"
			+ "\n  (c = cmX.capabilitymaterials_Capability_id and"
			+ "\n   (uc = c.capability_Max_Length_Unit and "
			+ "\n    (m = cmX.capabilitymaterials_Material_id and"
			+ "\n     (c = cc.capabilitycategories_Capability_id and"
			+ "\n      (posc = cc.capabilitycategories_ProductOrServiceCategory_id and"
			+ "\n       (uc.unitcode_Code=\"!__Q\".\"mm\" and"
			+ "\n        ((m.material_Material_Name=\"!__Q\".\"Pre-hardened Steel\" or m.material_Material_Name=\"!__Q\".\"17-4 Stainless Steel\") and"
			+ "\n         (posc.productorservicecategory_Category_Name=\"!__Q\".\"Sinker EDM\" or posc.productorservicecategory_Category_Name=\"!__Q\".\"Ram EDM\")"
			+ "\n)))))));"
			+ "\n} I"
			+ "\n*/"
			+ "\n"
			+ "\n/* "
			+ "\nNote changes to Q1:"
			+ "\n"
			+ "\nWHERE "
			+ "\n (Material.Material_Name='Pre-hardened Stainless Steel' Or Material.Material_Name='17-4 Stainless Steel')  //removed 'Stainless'"
			+ "\nAND"
			+ "\n (Capability.Max_Length>=15) // = 40, 47.25, 18.25 20 //OMMITTED "
			+ "\nAND "
			+ "\n (UnitCode.Code='cm') //changed to 'mm'"
			+ "\nAND "
			+ "\n (ProductOrServiceCategory.Category_Name='Sinker EDM' Or ProductOrServiceCategory.Category_Name='Ram EDM')"
			+ "\n*/"
			+ "\n"
			+ "\n////////////////////////////////////////"
			+ "\n"
			+ "\n//takes 30 mins"
			+ "\n/*"
			+ "\nQ2_pre = flower {"
			+ "\n select"
			+ "\n  c.capability_Capability_Name as cname,"
			+ "\n  c.capability_Max_Length as clen,"
			+ "\n  uc.unitcode_Code as ucd,"
			+ "\n  posc.productorservicecategory_Category_Name as pname;"
			+ "\n from"
			+ "\n  productorservicecategory as posc,"
			+ "\n  material as m,"
			+ "\n  unitcode as uc,"
			+ "\n  capability as c,"
			+ "\n  capabilitymaterials as cm,"
			+ "\n  capabilitycategories as cc;"
			+ "\n where"
			+ "\n  c = cm.capabilitymaterials_Capability_id,"
			+ "\n  uc = c.capability_Max_Length_Unit,"
			+ "\n  m = cm.capabilitymaterials_Material_id,"
			+ "\n  c = cc.capabilitycategories_Capability_id,"
			+ "\n  posc = cc.capabilitycategories_ProductOrServiceCategory_id;"
			+ "\n} I"
			+ "\n*/"
			+ "\n"
			+ "\n//kills gc after 30mins"
			+ "\n/*"
			+ "\nQ2 = FLOWER {"
			+ "\n select"
			+ "\n  c.capability_Capability_Name as cname,"
			+ "\n  c.capability_Max_Length as clen,"
			+ "\n  uc.unitcode_Code as ucd,"
			+ "\n  posc.productorservicecategory_Category_Name as pname;"
			+ "\n from"
			+ "\n  productorservicecategory as posc,"
			+ "\n  material as m,"
			+ "\n  unitcode as uc,"
			+ "\n  capability as c,"
			+ "\n  capabilitymaterials as cm,"
			+ "\n  capabilitycategories as cc;"
			+ "\n where"
			+ "\n  (c = cm.capabilitymaterials_Capability_id and"
			+ "\n  (uc = c.capability_Max_Length_Unit and"
			+ "\n  (m = cm.capabilitymaterials_Material_id and"
			+ "\n  (c = cc.capabilitycategories_Capability_id and"
			+ "\n  (posc = cc.capabilitycategories_ProductOrServiceCategory_id and"
			+ "\n  (uc.unitcode_Code = \"!__Q\".\"mm\" and"
			+ "\n   (posc.productorservicecategory_Category_Name=\"!__Q\".\"Small Hole EDM\" or "
			+ "\n    posc.productorservicecategory_Category_Name=\"!__Q\".\"Micro Hole EDM\")"
			+ "\n))))));"
			+ "\n} I"
			+ "\n*/"
			+ "\n"
			+ "\n/* note changes to Q2"
			+ "\nWHERE  "
			+ "\n(((Capability.Max_Length)>=8) //removed"
			+ "\n   AND ((UnitCode.Code)='cm') //changed to mm"
			+ "\n((ProductOrServiceCategory.Category_Name)='Small Hole EDM' Or (ProductOrServiceCategory.Category_Name)='Micro Hole EDM'));"
			+ "\n*/"
			+ "\n";


}
