package fql_lib.examples;

public class Patrick22Example extends Example {
	
	@Override
	public String isPatrick() {
		return "true";
	}

	@Override
	public String getName() {
		return "P NIST 4";
	}

	@Override
	public String getText() {
		return s;
	}
	
	String s = "old : type"
			+ "\n"
			+ "\nGlassCeramics: old"
			+ "\nGlass: old"
			+ "\nCrystalline: old"
			+ "\nNonCrystalline: old"
			+ "\nCeramic: old"
			+ "\nComposite: old"
			+ "\nMetal: old"
			+ "\nFerrous_old: old"
			+ "\nCastIron: old"
			+ "\nDieSteel: old"
			+ "\nSteel: old"
			+ "\nToolSteel: old"
			+ "\nStainlessSteel: old"
			+ "\nNonFerrous: old"
			+ "\nSuperAlloy: old"
			+ "\nStellite : old"
			+ "\nIconel: old"
			+ "\nHastelloy: old"
			+ "\nElastomer: old"
			+ "\nPlastic: old"
			+ "\nPolymer: old"
			+ "\nHermoset: old"
			+ "\nThermoPlastic: old"
			+ "\nNylon: old"
			+ "\nPVC: old"
			+ "\nPolyester: old"
			+ "\nMaterial: old"
			+ "\n"
			+ "\nnew : type"
			+ "\n"
			+ "\n\"Stainless Steel\" : new"
			+ "\n\"Tool Steel\" : new"
			+ "\n\"Plastics\" : new"
			+ "\n\"4140 Alloy Steels\" : new"
			+ "\n\"300 Stainless Steel\" : new"
			+ "\n\"Stainless Steel 302\" : new"
			+ "\n\"304 Stainless Steel\" : new"
			+ "\n\"316 Stainless Steel\" : new"
			+ "\n\"15-4 Stainless Steel\" : new"
			+ "\n\"17-4 Stainless Steel\" : new "
			+ "\n88 : new"
			+ "\n\"Micro Hole EDM\" : new"
			+ "\n\"Forging Dies\" : new"
			+ "\n\"Honing Machine\" : new"
			+ "\n\"A-2 Tool Steel\" : new"
			+ "\n\"Plastic Mold Making Services\" : new"
			+ "\n\"Ram EDM\" : new"
			+ "\n\"A-6 Tool Steel\" : new"
			+ "\n\"Blow Molds (Extrusion or Injection/Blow)\" : new"
			+ "\n118 : new"
			+ "\n\"Titanium\" : new"
			+ "\n\"I used the types of molds values from the Canyon Plastics.\" : new"
			+ "\n\"Non-Ferrous\" : new"
			+ "\n\"Tecomet\" : new"
			+ "\n\"Inch\" : new"
			+ "\n\"Wire EDM\" : new"
			+ "\n\"Verticle CNC Milling Machine\" : new"
			+ "\n\"Forgings\" : new"
			+ "\n0 : new"
			+ "\n\"Surface Grinder\" : new"
			+ "\n\"Titanium Alloy CP4\" : new"
			+ "\n\"Length measure in inches\" : new"
			+ "\n\"mm\" : new"
			+ "\n1 : new"
			+ "\n\"Each part/piece count\" : new"
			+ "\n\"CNC Machining\" : new"
			+ "\n\"0.005\" : new"
			+ "\n\"Pro Mold\" : new"
			+ "\n\"Marine\" : new"
			+ "\n\"\" : new"
			+ "\n\"P-20\" : new"
			+ "\n\"Transfer/Compression (Rubber or Silicone)\" : new"
			+ "\n\"Extrusion Dies\" : new"
			+ "\n\"Extrusions\" : new"
			+ "\n1000 : new"
			+ "\n\"Small Hole EDM\" : new"
			+ "\n\"D2 Tool Steel\" : new"
			+ "\n\"Machining\" : new"
			+ "\n\"Rotary Dies\" : new"
			+ "\n\"Plunger EDM\" : new"
			+ "\n\"Others\" : new"
			+ "\n\"This supplier has another capability registered under the Injection Molds category, but it is more about molding rather than making the mold. So I excluded that. It also has a separate capability profile about mold design that I excluded.\" : new"
			+ "\n\"Multi-Cavity/Family Injection Molds\" : new"
			+ "\n\"Lathe\" : new"
			+ "\n\"Optical\" : new"
			+ "\n\"Fully Hardened Tool Steel\" : new"
			+ "\n\"Titanium Alloy Ti 6AI-4V\" : new"
			+ "\n30 : new"
			+ "\n\"Collapsible Core\" : new"
			+ "\n\"High Speed Small Hole EDM\" : new"
			+ "\n\"Tool Steel 4340\" : new"
			+ "\n\"Food Processing\" : new"
			+ "\n\"Pre-hardened Stainless Steel\" : new"
			+ "\n\"Liquid Silicone Molds\" : new"
			+ "\n\"Aluminum\" : new"
			+ "\n\"4130 Tool Steel\" : new"
			+ "\n\"CNC 3-axis Milling Machine\" : new"
			+ "\n\"Chrome\" : new"
			+ "\n\"EDM Drilling\" : new"
			+ "\n\"Brass\" : new"
			+ "\n\"0.000001\" : new"
			+ "\n\"Die Cast Molds\" : new"
			+ "\n\"Mold Design and Build\" : new"
			+ "\n\"Alloy Steel\" : new"
			+ "\n\"No unit\" : new"
			+ "\n\"Electrical\" : new"
			+ "\n\"Stainless Steel 300 Series\" : new"
			+ "\n\"Carbon Steel\" : new"
			+ "\n\"cm\" : new"
			+ "\n\"Wire Electrical Discharge Machining\" : new"
			+ "\n\"EDM\" : new"
			+ "\n\"Aerospace\" : new"
			+ "\n\"Astro\" : new"
			+ "\n\"Complex & Difficult Machining\" : new"
			+ "\n\"B&B\" : new"
			+ "\n\"Wiegel Tool\" : new"
			+ "\n50 : new"
			+ "\n\"Length measure in millimeters\" : new"
			+ "\n\"Columbium\" : new"
			+ "\n\"Industrial\" : new"
			+ "\n\"Plastic Injection\" : new"
			+ "\n\"Injection Molds\" : new"
			+ "\n\"0.001\" : new"
			+ "\n\"Cobalt\" : new"
			+ "\n\"Automotive\" : new"
			+ "\n\"Klann Plastics and Canyon Plastics\" : new"
			+ "\n\"Custom  Molds for Plastic, Rubber, and Die Cast parts\" : new"
			+ "\n\"Medical\" : new"
			+ "\n\"EA\" : new"
			+ "\n\"Communication\" : new"
			+ "\n\"Prototype and Production Mold Design & Manufacturing\" : new"
			+ "\n\"Electrical Connectors\" : new"
			+ "\n\"Custom Manufacturing & Fabricating\" : new"
			+ "\n\"Hot Runners\" : new"
			+ "\n\"Music\" : new"
			+ "\n\"Dies & Molds\" : new"
			+ "\n\"Electrode Machining\" : new"
			+ "\n\"Military/Government\" : new"
			+ "\n1000000 : new"
			+ "\n\"Thousands\" : new"
			+ "\n\"Commercial\" : new"
			+ "\n\"Castings\" : new"
			+ "\n\"CNC 4-axis Milling Machine\" : new"
			+ "\n\"Industrial Tools & Die\" : new"
			+ "\n\"Sinker EDM\" : new"
			+ "\n\"Building/Construction\" : new"
			+ "\n\"CR/HR Steel\" : new"
			+ "\n\"Electronic\" : new"
			+ "\n\"0.0025\" : new"
			+ "\n\"CNC & Conventional Machining (turning & milling)\" : new"
			+ "\n\"Length measure in centimeters\" : new"
			+ "\n\"General machining\" : new"
			+ "\n\"Bobs Design\" : new"
			+ "\n\"Machinery Tools & Supplies\" : new"
			+ "\n\"Electrical Discharge Machining Services\" : new"
			+ "\n\"M2 Tool Steel\" : new"
			+ "\n\"NULL\" : new"
			+ "\n\"Titanium Alloy CP2\" : new"
			+ "\n\"CNC\" : new"
			+ "\n\"S7 Tool Steel\" : new"
			+ "\n\"Engraving Machine\" : new"
			+ "\n\"Consumer Goods\" : new"
			+ "\n\"Recreational Vehicle\" : new"
			+ "\n\"Jig Grinder\" : new"
			+ "\n\"1000 parts/pieces count\" : new"
			+ "\n\"Titanium Alloy Ti 6AI-4V ELI\" : new"
			+ "\n\"H-13 Tool Steel\" : new"
			+ "\n\"Inserts Only\" : new"
			+ "\n\"Ferrous\" : new"
			+ "\n"
			+ "\n/////////////////////////////////////////////////////////////////////////////////////////////////////////"
			+ "\n"
			+ "\nisa_preschema = schema {"
			+ "\n	nodes B;"
			+ "\n	edges f : B -> B, name : B -> old;"
			+ "\n	equations f.f.f.f.f = f.f.f.f;"
			+ "\n}"
			+ "\n"
			+ "\nisa_pre = instance {"
			+ "\n	variables"
			+ "\n	vGlassCeramics"
			+ "\n	vGlass"
			+ "\n	vCrystalline"
			+ "\n	vNonCrystalline"
			+ "\n	vCeramic"
			+ "\n	vComposite"
			+ "\n	vMetal"
			+ "\n	vFerrous"
			+ "\n	vCastIron"
			+ "\n	vDieSteel"
			+ "\n	vSteel"
			+ "\n	vToolSteel"
			+ "\n	vStainlessSteel"
			+ "\n	vNonFerrous"
			+ "\n	vSuperAlloy"
			+ "\n	vStellite "
			+ "\n	vIconel"
			+ "\n	vHastelloy"
			+ "\n	vElastomer"
			+ "\n	vPlastic"
			+ "\n	vPolymer"
			+ "\n	vHermoset"
			+ "\n	vThermoPlastic"
			+ "\n	vNylon"
			+ "\n	vPVC"
			+ "\n	vPolyester"
			+ "\n	vMaterial: B;"
			+ "\n	equations"
			+ "\n	vGlassCeramics.name = GlassCeramics,"
			+ "\n	vGlass.name = Glass,"
			+ "\n	vCrystalline.name = Crystalline,"
			+ "\n	vNonCrystalline.name = NonCrystalline,"
			+ "\n	vCeramic.name = Ceramic,"
			+ "\n	vComposite.name = Composite,"
			+ "\n	vMetal.name = Metal,"
			+ "\n	vFerrous.name = Ferrous_old,"
			+ "\n	vCastIron.name = CastIron,"
			+ "\n	vDieSteel.name = DieSteel, "
			+ "\n	vSteel.name = Steel,"
			+ "\n	vToolSteel.name = ToolSteel,"
			+ "\n	vStainlessSteel.name = StainlessSteel,"
			+ "\n	vNonFerrous.name = NonFerrous,"
			+ "\n	vSuperAlloy.name = SuperAlloy,"
			+ "\n	vStellite.name = Stellite,"
			+ "\n	vIconel.name = Iconel,"
			+ "\n	vHastelloy.name = Hastelloy,"
			+ "\n	vElastomer.name = Elastomer,"
			+ "\n	vPlastic.name = Plastic,"
			+ "\n	vPolymer.name = Polymer,"
			+ "\n	vHermoset.name = Hermoset,"
			+ "\n	vThermoPlastic.name = ThermoPlastic,"
			+ "\n	vNylon.name = Nylon,"
			+ "\n	vPVC.name = PVC,"
			+ "\n	vPolyester.name = Polyester,"
			+ "\n	vMaterial.name = Material,"
			+ "\n	vGlassCeramics.f = vNonCrystalline, "
			+ "\n	vGlass.f = vNonCrystalline, "
			+ "\n	vCrystalline.f = vCeramic, "
			+ "\n	vNonCrystalline.f = vCeramic, "
			+ "\n	vCeramic.f = vMaterial, "
			+ "\n	vComposite.f = vMaterial, "
			+ "\n	vMetal.f = vMaterial, "
			+ "\n	vFerrous.f = vMetal, "
			+ "\n	vNonFerrous.f = vMetal, "
			+ "\n	vSuperAlloy.f = vMetal, "
			+ "\n	vCastIron.f = vFerrous, "
			+ "\n	vDieSteel.f = vFerrous,"
			+ "\n	vSteel.f = vFerrous, "
			+ "\n	vToolSteel.f = vFerrous,"
			+ "\n	vStainlessSteel.f = vSteel,"
			+ "\n	vNonFerrous.f = vMetal, "
			+ "\n	vSuperAlloy.f = vMetal,"
			+ "\n	vStellite.f = vSuperAlloy, "
			+ "\n	vIconel.f = vSuperAlloy, "
			+ "\n	vHastelloy.f = vSuperAlloy,"
			+ "\n	vElastomer.f = vPolymer, "
			+ "\n	vPlastic.f = vPolymer, "
			+ "\n	vPolymer.f = vMaterial,"
			+ "\n	vHermoset.f = vPlastic, "
			+ "\n	vThermoPlastic.f = vPlastic,"
			+ "\n	vNylon.f = vThermoPlastic, "
			+ "\n	vPVC.f = vThermoPlastic, "
			+ "\n	vPolyester.f = vThermoPlastic,"
			+ "\n	vMaterial.f = vMaterial;"
			+ "\n} : isa_preschema"
			+ "\n"
			+ "\nisa_schema = schema {"
			+ "\n	nodes A, B;"
			+ "\n	edges l : A -> B, r : A -> B, name : B -> old;"
			+ "\n	equations;"
			+ "\n}"
			+ "\n"
			+ "\nisa = INSTANCE {"
			+ "\n	variables v1 v2 v3 v4 v5 v6 v7 v8 v11 v12 v13 v14 v15 v16 v17 v18 v19 v20 v21 v22 v23 v24 v25 v26 v27 v28 v29 : A,"
			+ "\n	vGlassCeramics"
			+ "\n	vGlass"
			+ "\n	vCrystalline"
			+ "\n	vNonCrystalline"
			+ "\n	vCeramic"
			+ "\n	vComposite"
			+ "\n	vMetal"
			+ "\n	vFerrous"
			+ "\n	vCastIron"
			+ "\n	vDieSteel"
			+ "\n	vSteel"
			+ "\n	vToolSteel"
			+ "\n	vStainlessSteel"
			+ "\n	vNonFerrous"
			+ "\n	vSuperAlloy"
			+ "\n	vStellite "
			+ "\n	vIconel"
			+ "\n	vHastelloy"
			+ "\n	vElastomer"
			+ "\n	vPlastic"
			+ "\n	vPolymer"
			+ "\n	vHermoset"
			+ "\n	vThermoPlastic"
			+ "\n	vNylon"
			+ "\n	vPVC"
			+ "\n	vPolyester"
			+ "\n	vMaterial: B;"
			+ "\n	equations"
			+ "\n	vGlassCeramics.name = GlassCeramics,"
			+ "\n	vGlass.name = Glass,"
			+ "\n	vCrystalline.name = Crystalline,"
			+ "\n	vNonCrystalline.name = NonCrystalline,"
			+ "\n	vCeramic.name = Ceramic,"
			+ "\n	vComposite.name = Composite,"
			+ "\n	vMetal.name = Metal,"
			+ "\n	vFerrous.name = Ferrous_old,"
			+ "\n	vCastIron.name = CastIron,"
			+ "\n	vDieSteel.name = DieSteel, "
			+ "\n	vSteel.name = Steel,"
			+ "\n	vToolSteel.name = ToolSteel,"
			+ "\n	vStainlessSteel.name = StainlessSteel,"
			+ "\n	vNonFerrous.name = NonFerrous,"
			+ "\n	vSuperAlloy.name = SuperAlloy,"
			+ "\n	vStellite.name = Stellite,"
			+ "\n	vIconel.name = Iconel,"
			+ "\n	vHastelloy.name = Hastelloy,"
			+ "\n	vElastomer.name = Elastomer,"
			+ "\n	vPlastic.name = Plastic,"
			+ "\n	vPolymer.name = Polymer,"
			+ "\n	vHermoset.name = Hermoset,"
			+ "\n	vThermoPlastic.name = ThermoPlastic,"
			+ "\n	vNylon.name = Nylon,"
			+ "\n	vPVC.name = PVC,"
			+ "\n	vPolyester.name = Polyester,"
			+ "\n	vMaterial.name = Material,"
			+ "\n	v1.l = vGlassCeramics, v1.r = vNonCrystalline, "
			+ "\n	v2.l = vGlass, v2.r = vNonCrystalline, "
			+ "\n	v3.l = vCrystalline, v3.r = vCeramic, "
			+ "\n	v4.l = vNonCrystalline, v4.r = vCeramic, "
			+ "\n	v5.l = vCeramic, v5.r = vMaterial, "
			+ "\n	v6.l = vComposite, v6.r = vMaterial, "
			+ "\n	v7.l = vMetal, v7.r = vMaterial, "
			+ "\n	v8.l = vFerrous, v8.r = vMetal, "
			+ "\n	v11.l= vCastIron, v11.r = vFerrous, "
			+ "\n	v12.l= vDieSteel, v12.r = vFerrous,"
			+ "\n	v13.l= vSteel, v13.r = vFerrous, "
			+ "\n	v14.l= vToolSteel, v14.r = vFerrous,"
			+ "\n	v15.l= vStainlessSteel, v15.r = vSteel,"
			+ "\n	v16.l= vNonFerrous, v16.r = vMetal, "
			+ "\n	v17.l= vSuperAlloy, v17.r = vMetal,"
			+ "\n	v18.l= vStellite, v18.r = vSuperAlloy, "
			+ "\n	v19.l= vIconel, v19.r = vSuperAlloy, "
			+ "\n	v20.l= vHastelloy, v20.r = vSuperAlloy,"
			+ "\n	v21.l= vElastomer, v21.r = vPolymer, "
			+ "\n	v22.l= vPlastic, v22.r = vPolymer, "
			+ "\n	v23.l= vPolymer, v23.r = vMaterial,"
			+ "\n	v24.l= vHermoset, v24.r = vPlastic, "
			+ "\n	v25.l= vThermoPlastic, v25.r = vPlastic,"
			+ "\n	v26.l= vNylon, v26.r = vThermoPlastic, "
			+ "\n	v27.l= vPVC, v27.r = vThermoPlastic, "
			+ "\n	v28.l= vPolyester, v28.r = vThermoPlastic,"
			+ "\n	v29.l= vMaterial, v29.r = vMaterial;"
			+ "\n} : isa_schema"
			+ "\n"
			+ "\nisa_schema_small = schema {"
			+ "\n	nodes A;"
			+ "\n	edges l : A -> old, r : A -> old;"
			+ "\n	equations;"
			+ "\n}"
			+ "\n"
			+ "\nM = mapping {"
			+ "\n	nodes A -> A;"
			+ "\n	edges l -> l.name, r -> r.name;"
			+ "\n} : isa_schema_small -> isa_schema "
			+ "\n"
			+ "\n//isa_small = delta M isa"
			+ "\n"
			+ "\nL0 = mapping {"
			+ "\n	nodes A -> B, B -> B;"
			+ "\n	edges l -> B, r -> B, name -> name;"
			+ "\n} : isa_schema -> isa_preschema"
			+ "\n"
			+ "\nL1 = mapping {"
			+ "\n	nodes A -> B, B -> B;"
			+ "\n	edges l -> B, r -> f, name -> name;"
			+ "\n} : isa_schema -> isa_preschema"
			+ "\n"
			+ "\nL2 = mapping {"
			+ "\n	nodes A -> B, B -> B;"
			+ "\n	edges l -> B, r -> f.f, name -> name;"
			+ "\n} : isa_schema -> isa_preschema"
			+ "\n"
			+ "\nL3 = mapping {"
			+ "\n	nodes A -> B, B -> B;"
			+ "\n	edges l -> B, r -> f.f.f, name -> name;"
			+ "\n} : isa_schema -> isa_preschema"
			+ "\n"
			+ "\nisa_rt0 = delta L0 isa_pre"
			+ "\nisa_rt1 = delta L1 isa_pre "
			+ "\nisa_rt2 = delta L2 isa_pre"
			+ "\nisa_rt3 = delta L3 isa_pre"
			+ "\n"
			+ "\nisa_rt = relationalize (isa_rt0 + (isa_rt1 + (isa_rt2 + isa_rt3)))"
			+ "\n"
			+ "\n//isa_rt_small = delta M isa_rt"
			+ "\n"
			+ "\n/////////////////////////////////////////////////////////////////////////////////////////////////////////"
			+ "\n"
			+ "\nsyn_schema = schema {"
			+ "\n	nodes C;"
			+ "\n	edges f : C -> old, g : C -> new;"
			+ "\n	equations;"
			+ "\n}"
			+ "\n "
			+ "\nsyn_inst = INSTANCE {"
			+ "\n   variables v1 v5 v7 v19 v20 v31 v32 v33 v34 v35 v36 : C;"
			+ "\n   equations"
			+ "\n	 v1.f = SuperAlloy, v1.g = \"4140 Alloy Steels\","
			+ "\n	 v5.f = StainlessSteel, v5.g = \"Stainless Steel\","
			+ "\n	 v7.f = ToolSteel, v7.g = \"Tool Steel\","
			+ "\n	 v19.f= Plastic, v19.g = Plastics,"
			+ "\n	 v20.f= Ferrous_old, v20.g = Ferrous,"
			+ "\n	 v31.f = StainlessSteel, v31.g = \"300 Stainless Steel\", "
			+ "\n      v32.f = StainlessSteel, v32.g = \"Stainless Steel 302\", "
			+ "\n      v33.f = StainlessSteel, v33.g = \"304 Stainless Steel\", "
			+ "\n      v34.f = StainlessSteel, v34.g = \"316 Stainless Steel\", "
			+ "\n      v35.f = StainlessSteel, v35.g = \"15-4 Stainless Steel\", "
			+ "\n      v36.f = StainlessSteel, v36.g = \"17-4 Stainless Steel\";"
			+ "\n} : syn_schema"
			+ "\n	"
			+ "\n/////////////////////////////////////////////////////////////////////////////////////////"
			+ "\n"
			+ "\ncombined = schema {"
			+ "\n	nodes A, B, C;"
			+ "\n	edges l : A  -> B , r : A  -> B , name : B  -> old, "
			+ "\n	      f : C -> old, g : C -> new;"
			+ "\n	equations;"
			+ "\n}"
			+ "\n"
			+ "\ninc1 = polynomial {"
			+ "\n	q1 = { for v:A; where; attributes; edges l={v=v.l}:q2, r={v=v.r}:q2; } : A,"
			+ "\n	q2 = { for v:B; where; attributes name=v.name; edges; } : B"
			+ "\n} : isa_schema -> combined"
			+ "\n"
			+ "\ninc2 = polynomial {"
			+ "\n	q1 = { for c:C; where; attributes f=c.f, g=c.g; edges; } : C"
			+ "\n} : syn_schema -> combined"
			+ "\n"
			+ "\ninst1 = apply inc1 isa_rt"
			+ "\ninst2 = apply inc2 syn_inst"
			+ "\ninst3 = (inst1 + inst2)"
			+ "\n"
			+ "\nisa_schema_small_new = schema {"
			+ "\n	nodes A;"
			+ "\n	edges l : A -> new, r : A -> new;"
			+ "\n	equations;"
			+ "\n}"
			+ "\n"
			+ "\nisa_schema_new = schema {"
			+ "\n	nodes A, B;"
			+ "\n	edges l : A -> B, r : A -> B, name : B -> new;"
			+ "\n	equations;"
			+ "\n}"
			+ "\n"
			+ "\nM_new = mapping {"
			+ "\n	nodes A -> A;"
			+ "\n	edges l -> l.name, r -> r.name;"
			+ "\n} : isa_schema_small_new -> isa_schema_new "
			+ "\n"
			+ "\nfq = polynomial {"
			+ "\n q1 = {for a:A, x:C, y:C; "
			+ "\n       where a.l.name=x.f, a.r.name=y.f;"
			+ "\n       attributes;"
			+ "\n       edges l = {c=x} : q2,"
			+ "\n             r = {c=y} : q2;"
			+ "\n       } : A,"
			+ "\n q2 = {for c:C; where; attributes name=c.g; edges;} : B"
			+ "\n} : combined -> isa_schema_new"
			+ "\n"
			+ "\nisa_syn = apply fq inst3"
			+ "\n"
			+ "\n//isa_syn_small = relationalize delta M_new isa_syn"
			+ "\n"
			+ "\n/////////////////////////////////////////////////////////////////////////////////////////"
			+ "\n"
			+ "\nrefl_closure = polynomial {"
			+ "\n q1 = {for b:B; where; attributes name=b.name; edges;} : B,"
			+ "\n q2 = {for a:A; "
			+ "\n       where; "
			+ "\n       attributes; "
			+ "\n       edges l = {b=a.l} : q1,"
			+ "\n             r = {b=a.r} : q1;"
			+ "\n } : A, "
			+ "\n q3 = {for b2:B;"
			+ "\n       where;"
			+ "\n       attributes;"
			+ "\n       edges l = {b=b2} : q1,"
			+ "\n             r = {b=b2} : q1;"
			+ "\n } : A "
			+ "\n} : isa_schema_new -> isa_schema_new"
			+ "\n"
			+ "\ntrans_step = polynomial {"
			+ "\n q1 = {for b:B; where; attributes name=b.name; edges;} : B,"
			+ "\n q2 = {for a:A; "
			+ "\n       where; "
			+ "\n       attributes; "
			+ "\n       edges l = {b=a.l} : q1,"
			+ "\n             r = {b=a.r} : q1;"
			+ "\n } : A, "
			+ "\n q3 = {for a1:A, a2:A;"
			+ "\n       where a1.r = a2.l;"
			+ "\n       attributes;"
			+ "\n       edges l = {b=a1.l} : q1,"
			+ "\n             r = {b=a2.r} : q1;"
			+ "\n } : A "
			+ "\n} : isa_schema_new -> isa_schema_new"
			+ "\n"
			+ "\nalmost2 = apply refl_closure isa_syn "
			+ "\nalmost3 = relationalize apply trans_step almost2 //takes 15 minutes"
			+ "\n//almost4 = relationalize apply trans_step almost3 //never terminates"
			+ "\n"
			+ "\n//done = delta M_new almost3"
			+ "\n";




}
