/* The following code was generated by JFlex 1.4.3 on 10/10/14 7:10 PM */

/*
 * Generated on 10/10/14 7:10 PM
 */
package fql_lib.X;

import java.io.*;
import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.*;


/**
 * 
 */

public class FpqlTokenMaker extends AbstractJFlexCTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int EOL_COMMENT = 4;
  public static final int YYINITIAL = 0;
  public static final int MLC = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\17\1\7\1\0\1\17\1\15\22\0\1\17\1\24\1\14"+
    "\1\16\1\1\1\24\1\24\1\6\1\25\1\25\1\21\1\24\1\24"+
    "\1\53\1\23\1\20\1\4\3\4\4\4\2\3\1\36\1\24\1\15"+
    "\1\55\1\54\1\24\1\16\6\5\24\1\1\25\1\10\1\25\1\15"+
    "\1\2\1\0\1\40\1\13\1\42\1\45\1\35\1\32\1\46\1\26"+
    "\1\33\2\1\1\34\1\41\1\44\1\43\1\30\1\52\1\12\1\31"+
    "\1\27\1\11\1\51\1\37\1\1\1\50\1\47\1\22\1\15\1\22"+
    "\1\24\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\2\1\1\2\1\3\2\1\1\4\1\5\1\1"+
    "\1\6\7\1\1\7\7\1\1\10\1\11\5\10\1\12"+
    "\3\10\1\0\1\13\2\1\2\4\1\14\1\15\1\16"+
    "\2\1\1\17\21\1\1\20\11\0\2\1\1\4\1\21"+
    "\1\4\17\1\11\0\2\1\1\4\13\1\2\0\1\22"+
    "\2\0\1\23\1\0\2\1\1\4\3\1\1\24\4\1"+
    "\5\0\1\1\1\4\23\1";

  private static int [] zzUnpackAction() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\270\0\346\0\212\0\u0114"+
    "\0\u0142\0\u0170\0\u019e\0\u01cc\0\212\0\u01fa\0\u0228\0\u0256"+
    "\0\u0284\0\u02b2\0\u02e0\0\u030e\0\212\0\u033c\0\u036a\0\u0398"+
    "\0\u03c6\0\u03f4\0\u0422\0\u0450\0\u047e\0\212\0\u04ac\0\u04da"+
    "\0\u0508\0\u0536\0\u0564\0\212\0\u0592\0\u05c0\0\u05ee\0\u061c"+
    "\0\u064a\0\u0678\0\u06a6\0\u06d4\0\u0702\0\212\0\212\0\212"+
    "\0\u0730\0\u075e\0\270\0\u078c\0\u07ba\0\u07e8\0\u0816\0\u0844"+
    "\0\u0872\0\u08a0\0\u08ce\0\u08fc\0\u092a\0\u0958\0\u0986\0\u09b4"+
    "\0\u09e2\0\u0a10\0\u0a3e\0\u0a6c\0\212\0\u0a9a\0\u0ac8\0\u0af6"+
    "\0\u0b24\0\u0b52\0\u0b80\0\u0bae\0\u0bdc\0\u0c0a\0\u0c38\0\u0c66"+
    "\0\u0c94\0\212\0\u0cc2\0\u0cf0\0\u0d1e\0\u0d4c\0\u0d7a\0\u0da8"+
    "\0\u0dd6\0\u0e04\0\u0e32\0\u0e60\0\u0e8e\0\u0ebc\0\u0eea\0\u0f18"+
    "\0\u0f46\0\u0f74\0\u0fa2\0\u0fd0\0\u0ffe\0\u102c\0\u105a\0\u1088"+
    "\0\u10b6\0\u10e4\0\u1112\0\u1140\0\u116e\0\u119c\0\u11ca\0\u11f8"+
    "\0\u1226\0\u1254\0\u1282\0\u12b0\0\u12de\0\u130c\0\u133a\0\u1368"+
    "\0\u1396\0\u13c4\0\u13f2\0\u1420\0\u144e\0\u147c\0\u14aa\0\u14d8"+
    "\0\u1506\0\u1534\0\u1562\0\u1590\0\u15be\0\u15ec\0\270\0\u161a"+
    "\0\u1648\0\u1676\0\u16a4\0\u16d2\0\u1420\0\u1700\0\u14aa\0\u172e"+
    "\0\u175c\0\u178a\0\u17b8\0\u17e6\0\u1814\0\u1842\0\u1870\0\u189e"+
    "\0\u18cc\0\u18fa\0\u1928\0\u1956\0\u1984\0\u19b2\0\u19e0\0\u1a0e"+
    "\0\u1a3c\0\u1a6a\0\u1a98\0\u1ac6\0\u1af4";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\2\6\1\5\1\4\1\7\1\4\1\10"+
    "\1\11\1\5\1\12\2\4\1\13\1\14\1\4\1\15"+
    "\2\4\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\5\1\24\1\25\1\5\1\26\1\27\1\30\1\5"+
    "\1\31\1\32\3\5\1\33\1\5\1\34\1\4\1\25"+
    "\7\35\1\36\11\35\1\37\4\35\1\40\3\35\1\41"+
    "\4\35\1\42\16\35\7\43\1\44\16\43\1\45\3\43"+
    "\1\46\4\43\1\47\16\43\57\0\5\5\2\0\1\50"+
    "\3\5\12\0\10\5\1\0\14\5\3\0\3\51\2\6"+
    "\1\51\2\0\4\51\2\0\1\51\7\0\10\51\1\0"+
    "\14\51\4\0\5\5\2\0\1\50\3\5\12\0\10\5"+
    "\1\0\5\5\1\52\6\5\4\0\5\5\2\0\1\50"+
    "\3\5\12\0\7\5\1\53\1\0\14\5\3\0\7\12"+
    "\1\54\1\55\3\12\1\56\41\12\17\0\1\13\56\0"+
    "\1\57\1\60\35\0\5\5\2\0\1\50\3\5\12\0"+
    "\10\5\1\0\4\5\1\61\7\5\4\0\5\5\2\0"+
    "\1\50\1\5\1\62\1\5\12\0\1\5\1\63\6\5"+
    "\1\0\11\5\1\64\2\5\4\0\5\5\2\0\1\50"+
    "\3\5\12\0\5\5\1\63\2\5\1\0\1\5\1\65"+
    "\12\5\4\0\5\5\2\0\1\50\3\5\12\0\5\5"+
    "\1\66\2\5\1\0\3\5\1\67\1\5\1\70\6\5"+
    "\4\0\5\5\2\0\1\50\3\5\12\0\3\5\1\71"+
    "\1\63\3\5\1\0\5\5\1\63\6\5\4\0\5\5"+
    "\2\0\1\50\3\5\12\0\10\5\1\0\5\5\1\72"+
    "\6\5\4\0\5\5\2\0\1\50\3\5\12\0\10\5"+
    "\1\0\6\5\1\73\4\5\1\74\4\0\5\5\2\0"+
    "\1\50\3\5\12\0\3\5\1\75\4\5\1\0\14\5"+
    "\4\0\5\5\2\0\1\50\3\5\12\0\10\5\1\0"+
    "\1\5\1\76\12\5\4\0\5\5\2\0\1\50\3\5"+
    "\12\0\10\5\1\0\1\5\1\77\2\5\1\100\7\5"+
    "\4\0\5\5\2\0\1\50\3\5\12\0\10\5\1\0"+
    "\4\5\1\101\7\5\4\0\5\5\2\0\1\50\3\5"+
    "\12\0\7\5\1\102\1\0\14\5\4\0\5\5\2\0"+
    "\1\50\3\5\12\0\10\5\1\0\1\5\1\103\2\5"+
    "\1\104\7\5\57\0\1\25\1\0\7\35\1\0\11\35"+
    "\1\0\4\35\1\0\3\35\1\0\4\35\1\0\16\35"+
    "\20\0\1\105\64\0\1\106\55\0\1\107\3\0\1\110"+
    "\61\0\1\111\16\0\7\43\1\0\16\43\1\0\3\43"+
    "\1\0\4\43\1\0\16\43\27\0\1\112\55\0\1\113"+
    "\3\0\1\114\61\0\1\115\27\0\1\116\44\0\6\51"+
    "\2\0\4\51\2\0\1\51\7\0\10\51\1\0\14\51"+
    "\4\0\5\5\2\0\1\50\3\5\12\0\5\5\1\71"+
    "\2\5\1\0\14\5\4\0\5\5\2\0\1\50\3\5"+
    "\12\0\1\5\1\117\4\5\1\120\1\5\1\0\14\5"+
    "\3\0\10\54\1\121\3\54\1\122\45\54\1\12\1\54"+
    "\1\12\1\0\1\12\1\123\3\12\12\54\1\12\2\54"+
    "\1\12\11\54\1\12\11\54\1\0\5\5\2\0\1\50"+
    "\3\5\12\0\10\5\1\0\2\5\1\124\11\5\4\0"+
    "\5\5\2\0\1\50\3\5\12\0\10\5\1\0\1\5"+
    "\1\125\12\5\4\0\5\5\2\0\1\50\3\5\12\0"+
    "\2\5\1\126\5\5\1\0\14\5\4\0\5\5\2\0"+
    "\1\50\3\5\12\0\5\5\1\127\2\5\1\0\14\5"+
    "\4\0\5\5\2\0\1\50\3\5\12\0\10\5\1\0"+
    "\7\5\1\130\4\5\4\0\5\5\2\0\1\50\3\5"+
    "\12\0\1\131\7\5\1\0\14\5\4\0\5\5\2\0"+
    "\1\50\3\5\12\0\10\5\1\0\6\5\1\63\5\5"+
    "\4\0\5\5\2\0\1\50\3\5\12\0\1\5\1\63"+
    "\6\5\1\0\14\5\4\0\5\5\2\0\1\50\1\5"+
    "\1\63\1\5\12\0\3\5\1\132\2\5\1\63\1\5"+
    "\1\0\14\5\4\0\5\5\2\0\1\50\3\5\12\0"+
    "\10\5\1\0\7\5\1\133\4\5\4\0\5\5\2\0"+
    "\1\50\1\134\2\5\12\0\10\5\1\0\14\5\4\0"+
    "\5\5\2\0\1\50\3\5\12\0\3\5\1\135\4\5"+
    "\1\0\14\5\4\0\5\5\2\0\1\50\3\5\12\0"+
    "\2\5\1\136\5\5\1\0\14\5\4\0\5\5\2\0"+
    "\1\50\3\5\12\0\3\5\1\126\4\5\1\0\14\5"+
    "\4\0\5\5\2\0\1\50\1\5\1\137\1\5\12\0"+
    "\10\5\1\0\5\5\1\140\6\5\4\0\5\5\2\0"+
    "\1\50\3\5\12\0\10\5\1\0\6\5\1\133\5\5"+
    "\4\0\5\5\2\0\1\50\3\5\12\0\6\5\1\141"+
    "\1\5\1\0\14\5\4\0\5\5\2\0\1\50\1\5"+
    "\1\142\1\5\12\0\10\5\1\0\14\5\4\0\5\5"+
    "\2\0\1\50\3\5\12\0\5\5\1\70\2\5\1\0"+
    "\14\5\32\0\1\143\56\0\1\144\61\0\1\145\60\0"+
    "\1\146\45\0\1\147\56\0\1\150\61\0\1\151\60\0"+
    "\1\152\21\0\3\153\5\0\1\153\16\0\1\153\2\0"+
    "\1\153\2\0\1\153\1\0\1\153\2\0\1\153\11\0"+
    "\5\5\2\0\1\50\1\154\2\5\12\0\10\5\1\0"+
    "\14\5\4\0\5\5\2\0\1\50\3\5\12\0\10\5"+
    "\1\0\1\5\1\155\12\5\3\0\7\54\1\0\51\54"+
    "\3\156\2\54\1\121\2\54\1\156\1\122\15\54\1\156"+
    "\2\54\1\156\2\54\1\156\1\54\1\156\2\54\1\156"+
    "\10\54\1\0\5\5\2\0\1\50\3\5\12\0\10\5"+
    "\1\0\4\5\1\157\7\5\4\0\5\5\2\0\1\50"+
    "\3\5\12\0\10\5\1\0\5\5\1\160\6\5\4\0"+
    "\5\5\2\0\1\50\3\5\12\0\7\5\1\63\1\0"+
    "\14\5\4\0\5\5\2\0\1\50\1\5\1\63\1\5"+
    "\12\0\10\5\1\0\14\5\4\0\5\5\2\0\1\50"+
    "\3\5\12\0\10\5\1\0\2\5\1\161\11\5\4\0"+
    "\5\5\2\0\1\50\3\5\12\0\7\5\1\130\1\0"+
    "\14\5\4\0\5\5\2\0\1\50\3\5\12\0\1\5"+
    "\1\162\6\5\1\0\14\5\4\0\5\5\2\0\1\50"+
    "\3\5\12\0\7\5\1\163\1\0\14\5\4\0\5\5"+
    "\2\0\1\50\3\5\12\0\10\5\1\0\1\5\1\164"+
    "\12\5\4\0\5\5\2\0\1\50\1\165\2\5\12\0"+
    "\10\5\1\0\14\5\4\0\5\5\2\0\1\50\3\5"+
    "\12\0\2\5\1\166\5\5\1\0\14\5\4\0\5\5"+
    "\2\0\1\50\3\5\12\0\7\5\1\167\1\0\14\5"+
    "\4\0\5\5\2\0\1\50\3\5\12\0\3\5\1\170"+
    "\4\5\1\0\14\5\4\0\5\5\2\0\1\50\3\5"+
    "\12\0\1\5\1\161\6\5\1\0\14\5\4\0\5\5"+
    "\2\0\1\50\3\5\12\0\5\5\1\171\2\5\1\0"+
    "\14\5\33\0\1\172\63\0\1\173\54\0\1\144\43\0"+
    "\1\174\62\0\1\175\63\0\1\176\54\0\1\150\43\0"+
    "\1\177\35\0\3\200\5\0\1\200\16\0\1\200\2\0"+
    "\1\200\2\0\1\200\1\0\1\200\2\0\1\200\11\0"+
    "\5\5\2\0\1\50\1\5\1\201\1\5\12\0\10\5"+
    "\1\0\14\5\4\0\5\5\2\0\1\50\3\5\12\0"+
    "\1\5\1\202\6\5\1\0\14\5\3\0\3\54\3\203"+
    "\2\54\1\121\2\54\1\203\1\122\15\54\1\203\2\54"+
    "\1\203\2\54\1\203\1\54\1\203\2\54\1\203\10\54"+
    "\1\0\5\5\2\0\1\50\3\5\12\0\10\5\1\0"+
    "\2\5\1\204\11\5\4\0\5\5\2\0\1\50\3\5"+
    "\12\0\3\5\1\205\4\5\1\0\14\5\4\0\5\5"+
    "\2\0\1\50\3\5\12\0\10\5\1\0\1\5\1\63"+
    "\12\5\4\0\5\5\2\0\1\50\3\5\12\0\10\5"+
    "\1\0\1\5\1\206\12\5\4\0\5\5\2\0\1\50"+
    "\3\5\12\0\3\5\1\207\4\5\1\0\14\5\4\0"+
    "\5\5\2\0\1\50\3\5\12\0\1\5\1\210\6\5"+
    "\1\0\14\5\4\0\5\5\2\0\1\50\3\5\12\0"+
    "\10\5\1\0\2\5\1\126\11\5\4\0\5\5\2\0"+
    "\1\50\3\5\12\0\5\5\1\211\2\5\1\0\14\5"+
    "\4\0\5\5\2\0\1\50\3\5\12\0\1\5\1\117"+
    "\6\5\1\0\14\5\4\0\5\5\2\0\1\50\3\5"+
    "\12\0\1\5\1\212\6\5\1\0\14\5\4\0\5\5"+
    "\2\0\1\50\3\5\12\0\10\5\1\0\1\5\1\213"+
    "\12\5\34\0\1\144\4\0\1\173\37\0\1\214\36\0"+
    "\1\174\1\215\3\174\1\215\2\0\3\174\2\0\1\215"+
    "\1\0\1\174\1\215\1\0\3\215\10\174\1\215\14\174"+
    "\1\215\1\0\1\215\31\0\1\150\4\0\1\176\37\0"+
    "\1\216\36\0\1\177\1\217\3\177\1\217\2\0\3\177"+
    "\2\0\1\217\1\0\1\177\1\217\1\0\3\217\10\177"+
    "\1\217\14\177\1\217\1\0\1\217\3\0\3\220\5\0"+
    "\1\220\16\0\1\220\2\0\1\220\2\0\1\220\1\0"+
    "\1\220\2\0\1\220\11\0\5\5\2\0\1\50\3\5"+
    "\12\0\10\5\1\0\5\5\1\63\6\5\4\0\5\5"+
    "\2\0\1\50\3\5\12\0\5\5\1\221\2\5\1\0"+
    "\14\5\3\0\3\54\3\222\2\54\1\121\2\54\1\222"+
    "\1\122\15\54\1\222\2\54\1\222\2\54\1\222\1\54"+
    "\1\222\2\54\1\222\10\54\1\0\5\5\2\0\1\50"+
    "\3\5\12\0\10\5\1\0\4\5\1\223\7\5\4\0"+
    "\5\5\2\0\1\50\3\5\12\0\4\5\1\224\3\5"+
    "\1\0\14\5\4\0\5\5\2\0\1\50\3\5\12\0"+
    "\10\5\1\0\5\5\1\225\6\5\4\0\5\5\2\0"+
    "\1\50\3\5\12\0\5\5\1\226\2\5\1\0\14\5"+
    "\4\0\5\5\2\0\1\50\3\5\12\0\10\5\1\0"+
    "\5\5\1\227\6\5\4\0\5\5\2\0\1\50\3\5"+
    "\12\0\10\5\1\0\1\5\1\230\12\5\4\0\5\5"+
    "\2\0\1\50\2\5\1\231\12\0\10\5\1\0\14\5"+
    "\23\0\1\174\55\0\1\177\40\0\3\5\5\0\1\5"+
    "\16\0\1\5\2\0\1\5\2\0\1\5\1\0\1\5"+
    "\2\0\1\5\11\0\5\5\2\0\1\50\3\5\12\0"+
    "\10\5\1\0\4\5\1\232\7\5\3\0\3\54\3\12"+
    "\2\54\1\121\2\54\1\12\1\122\15\54\1\12\2\54"+
    "\1\12\2\54\1\12\1\54\1\12\2\54\1\12\10\54"+
    "\1\0\5\5\2\0\1\50\1\5\1\233\1\5\12\0"+
    "\10\5\1\0\14\5\4\0\5\5\2\0\1\50\3\5"+
    "\12\0\10\5\1\0\4\5\1\234\7\5\4\0\5\5"+
    "\2\0\1\50\3\5\12\0\10\5\1\0\3\5\1\126"+
    "\10\5\4\0\5\5\2\0\1\50\3\5\12\0\10\5"+
    "\1\0\4\5\1\235\7\5\4\0\5\5\2\0\1\50"+
    "\3\5\12\0\10\5\1\0\7\5\1\63\4\5\4\0"+
    "\5\5\2\0\1\50\3\5\12\0\10\5\1\0\5\5"+
    "\1\71\6\5\4\0\5\5\2\0\1\50\3\5\12\0"+
    "\6\5\1\133\1\5\1\0\14\5\4\0\5\5\2\0"+
    "\1\50\3\5\12\0\10\5\1\0\5\5\1\236\6\5"+
    "\4\0\5\5\2\0\1\50\3\5\12\0\2\5\1\237"+
    "\5\5\1\0\14\5\4\0\5\5\2\0\1\50\1\5"+
    "\1\240\1\5\12\0\10\5\1\0\14\5\4\0\5\5"+
    "\2\0\1\50\3\5\12\0\10\5\1\0\5\5\1\163"+
    "\6\5\4\0\5\5\2\0\1\50\3\5\12\0\10\5"+
    "\1\0\1\5\1\241\12\5\4\0\5\5\2\0\1\50"+
    "\3\5\12\0\1\242\7\5\1\0\14\5\4\0\5\5"+
    "\2\0\1\50\3\5\12\0\10\5\1\0\2\5\1\63"+
    "\11\5\4\0\5\5\2\0\1\50\3\5\12\0\6\5"+
    "\1\243\1\5\1\0\14\5\4\0\5\5\2\0\1\50"+
    "\3\5\12\0\5\5\1\244\2\5\1\0\14\5\4\0"+
    "\5\5\2\0\1\50\3\5\12\0\5\5\1\245\2\5"+
    "\1\0\14\5\4\0\5\5\2\0\1\50\3\5\12\0"+
    "\3\5\1\240\4\5\1\0\14\5\4\0\5\5\2\0"+
    "\1\50\3\5\12\0\10\5\1\0\10\5\1\126\3\5"+
    "\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6946];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\2\1\1\11\5\1\1\11\7\1\1\11"+
    "\10\1\1\11\5\1\1\11\3\1\1\0\5\1\3\11"+
    "\24\1\1\11\11\0\3\1\1\11\20\1\11\0\16\1"+
    "\2\0\1\1\2\0\1\1\1\0\13\1\5\0\25\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */


	/**
	 * Constructor.  This must be here because JFlex does not generate a
	 * no-parameter constructor.
	 */
	public FpqlTokenMaker() {
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addToken(int, int, int)
	 */
	private void addHyperlinkToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, true);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int tokenType) {
		addToken(zzStartRead, zzMarkedPos-1, tokenType);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addHyperlinkToken(int, int, int)
	 */
	private void addToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, false);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param array The character array.
	 * @param start The starting offset in the array.
	 * @param end The ending offset in the array.
	 * @param tokenType The token's type.
	 * @param startOffset The offset in the document at which this token
	 *        occurs.
	 * @param hyperlink Whether this token is a hyperlink.
	 */
	public void addToken(char[] array, int start, int end, int tokenType,
						int startOffset, boolean hyperlink) {
		super.addToken(array, start,end, tokenType, startOffset, hyperlink);
		zzStartRead = zzMarkedPos;
	}


	/**
	 * Returns the text to place at the beginning and end of a
	 * line to "comment" it in a this programming language.
	 *
	 * @return The start and end strings to add to a line to "comment"
	 *         it out.
	 */
	public String[] getLineCommentStartAndEnd() {
		return new String[] { "//", null };
	}


	/**
	 * Returns the first token in the linked list of tokens generated
	 * from <code>text</code>.  This method must be implemented by
	 * subclasses so they can correctly implement syntax highlighting.
	 *
	 * @param text The text from which to get tokens.
	 * @param initialTokenType The token type we should start with.
	 * @param startOffset The offset into the document at which
	 *        <code>text</code> starts.
	 * @return The first <code>Token</code> in a linked list representing
	 *         the syntax highlighted text.
	 */
	public Token getTokenList(Segment text, int initialTokenType, int startOffset) {

		resetTokenList();
		this.offsetShift = -text.offset + startOffset;

		// Start off in the proper state.
		int state = Token.NULL;
		switch (initialTokenType) {
						case Token.COMMENT_MULTILINE:
				state = MLC;
				start = text.offset;
				break;

			/* No documentation comments */
			default:
				state = Token.NULL;
		}

		s = text;
		try {
			yyreset(zzReader);
			yybegin(state);
			return yylex();
		} catch (IOException ioe) {
			ioe.printStackTrace();
			return null;
		}

	}


	/**
	 * Refills the input buffer.
	 *
	 * @return      <code>true</code> if EOF was reached, otherwise
	 *              <code>false</code>.
	 */
	private boolean zzRefill() {
		return zzCurrentPos>=s.offset+s.count;
	}


	/**
	 * Resets the scanner to read from a new input stream.
	 * Does not close the old reader.
	 *
	 * All internal variables are reset, the old input stream 
	 * <b>cannot</b> be reused (internal buffer is discarded and lost).
	 * Lexical state is set to <tt>YY_INITIAL</tt>.
	 *
	 * @param reader   the new input stream 
	 */
	public final void yyreset(Reader reader) {
		// 's' has been updated.
		zzBuffer = s.array;
		/*
		 * We replaced the line below with the two below it because zzRefill
		 * no longer "refills" the buffer (since the way we do it, it's always
		 * "full" the first time through, since it points to the segment's
		 * array).  So, we assign zzEndRead here.
		 */
		//zzStartRead = zzEndRead = s.offset;
		zzStartRead = s.offset;
		zzEndRead = zzStartRead + s.count - 1;
		zzCurrentPos = zzMarkedPos = zzPushbackPos = s.offset;
		zzLexicalState = YYINITIAL;
		zzReader = reader;
		zzAtBOL  = true;
		zzAtEOF  = false;
	}




  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public FpqlTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public FpqlTokenMaker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 3: 
          { addNullToken(); return firstToken;
          }
        case 21: break;
        case 14: 
          { start = zzMarkedPos-2; yybegin(MLC);
          }
        case 22: break;
        case 5: 
          { addToken(Token.WHITESPACE);
          }
        case 23: break;
        case 17: 
          { addToken(Token.ERROR_STRING_DOUBLE);
          }
        case 24: break;
        case 15: 
          { addToken(Token.RESERVED_WORD);
          }
        case 25: break;
        case 6: 
          { addToken(Token.SEPARATOR);
          }
        case 26: break;
        case 1: 
          { addToken(Token.IDENTIFIER);
          }
        case 27: break;
        case 10: 
          { addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
          }
        case 28: break;
        case 13: 
          { start = zzMarkedPos-2; yybegin(EOL_COMMENT);
          }
        case 29: break;
        case 4: 
          { addToken(Token.ERROR_STRING_DOUBLE); addNullToken(); return firstToken;
          }
        case 30: break;
        case 16: 
          { yybegin(YYINITIAL); addToken(start,zzStartRead+2-1, Token.COMMENT_MULTILINE);
          }
        case 31: break;
        case 12: 
          { addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
          }
        case 32: break;
        case 19: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_EOL); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_EOL); start = zzMarkedPos;
          }
        case 33: break;
        case 18: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_MULTILINE); start = zzMarkedPos;
          }
        case 34: break;
        case 20: 
          { addToken(Token.RESERVED_WORD_2);
          }
        case 35: break;
        case 11: 
          { addToken(Token.ERROR_NUMBER_FORMAT);
          }
        case 36: break;
        case 2: 
          { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
          }
        case 37: break;
        case 7: 
          { addToken(Token.OPERATOR);
          }
        case 38: break;
        case 8: 
          { 
          }
        case 39: break;
        case 9: 
          { addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
          }
        case 40: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case EOL_COMMENT: {
              addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
            }
            case 166: break;
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 167: break;
            case MLC: {
              addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
            }
            case 168: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
